// PHYSIOLOGIE S2 — organised.
//
// Neurophysiology. The largest module in the Drive at 327 files, and most of
// that weight is question material: an ED and exam archive going back to 2009,
// Ben Cheikh's QCM photographed page by page, isolés for every chapter with
// their corrections. The lectures themselves are twenty, taught by Dougui and
// Ben Cheikh, kept three times over as 2023 scans, 2024 PDFs and the original
// PowerPoints.
//
// Whole exams photographed one page per image are one exam here, pages in
// order, not fifty files called IMG-20210616-WA00xx.

const P = 'PDF';
const J = 'JPG';

export const PHYSIOLOGIE_S2 = {
  id: 'physiologie-s2', promo: 'pcem2', semester: 'S2',
  name: 'PHYSIOLOGIE S2', icon: 'atom', tint: 'purple',
  professors: ['Dougui', 'Ben Cheikh'],

  chapters: [
    {
      title: 'Systèmes sensitivo-sensoriels',
      subtitle: 'Somesthésie, douleur, vision, audition, olfaction, gustation',
      lectures: [
        { n: 1, title: 'Les systèmes sensitivo-sensoriels — généralités', ext: P, mb: '0.9', fid: '188wmR-Fr2WUcCNhKOxpHVKJ27X8GsaOe', year: 2024,
          versions: [
            { title: 'Systèmes sensoriels', prof: 'Dougui', year: 2022, ext: 'PPTX', mb: '0.8', fid: '1e1fWOuW7kvIcQtxcbCJuZykmn51rZh5C' },
            { title: 'Systèmes sensoriels', prof: 'Dougui', year: 2019, ext: 'PPTX', mb: '0.6', fid: '1UmRDnrmbVRauTpIVXFar7MG4mo72KXdP' },
          ] },
        { n: 2, title: 'La somesthésie', ext: P, mb: '2.4', fid: '1pVx64pDzfqzKP_jsWhlepDQ2bposrAjG', year: 2024,
          versions: [
            { title: 'La somesthésie', year: 2023, mb: '24.2', fid: '1uw4wulHvLpRnRNb9_TbdtyHCN3x8I7Hp' },
            { title: 'La somesthésie', prof: 'Dougui', year: 2022, ext: 'PPTX', mb: '1.8', fid: '1hfuDya2P11f2Bl9e3WZDDUebXyGeFH_J' },
            { title: 'La somesthésie — polycopié détaillé', year: 2015, mb: '0.2', fid: '1juPc3Vl4kTppzo_dad0ecHf4MmfnmXFz' },
          ] },
        { n: 3, title: 'La nociception et la douleur', ext: P, mb: '11.8', fid: '1P-qoZ4ek9xV86vi1XUUFBLvoHkaMT8GA', year: 2024,
          versions: [
            { title: 'La nociception', year: 2023, mb: '17.1', fid: '1bwDIhrheNWZH-eb8F-n7mLpK59Wt0y-8' },
            { title: 'La nociception (2)', year: 2023, mb: '15.8', fid: '1qbKFEKfewj__glvzcTq-v8WbQzfF2Wuo' },
            { title: 'La douleur', prof: 'Dougui', year: 2019, ext: 'PPTX', mb: '1.8', fid: '1cCkZQNnN7IVL6fPBcdePtf697zG3jVcX' },
          ] },
        { n: 4, title: 'La vision', ext: P, mb: '2.1', fid: '1h2RuQbXG6GBQqUrNGlaIIeIyVUVO-LWA', year: 2024,
          versions: [
            { title: 'Physiologie de la vision', year: 2023, mb: '27.4', fid: '1_USY5Og_16Cm1kJeNWyZZKtfzPBQKCGW' },
            { title: "Physiologie de l'œil", year: 2023, mb: '27.4', fid: '1AZ2yMbVHF1eSoa1n4IYQuHMqfuXYqnYW' },
            { title: 'La vision', prof: 'Dougui', year: 2022, ext: 'PPTX', mb: '4.7', fid: '1qDUypC5a8_7RKnffSABeRDgEojTynETq' },
          ] },
        { n: 5, title: "L'audition", ext: P, mb: '0.9', fid: '1ZB14HmLdgFzoNq03lvQhYxLtiUV4ioVf', year: 2024,
          versions: [
            { title: 'Physiologie auditive', year: 2023, mb: '23.2', fid: '1HrEm6AFtznVfLVPYCpd5Iq_JKe93oIjJ' },
            { title: "L'audition", prof: 'Dougui', year: 2019, ext: 'PPTX', mb: '2.2', fid: '1Yh4czz6b-TXUGOaBqwo4ltCr1BsErLXg' },
          ] },
        { n: 6, title: "L'olfaction et la gustation", ext: P, mb: '19.4', fid: '1QBcSdfXWSgyQXvDhADksEMFT72w_08F7', year: 2023 },
      ],
    },
    {
      title: 'Motricité',
      subtitle: 'Réflexes, tonus, équilibre, cervelet, noyaux gris centraux',
      lectures: [
        { n: 7, title: 'La motricité somatique', ext: P, mb: '3.4', fid: '17dufqhqE_fcuDCGUTRJZWTLfq66eIS2R', year: 2024,
          versions: [
            { title: 'La motricité somatique', year: 2023, mb: '1.7', fid: '1PsPhVZ3-4LLDxghI9AOYikCLXF827PBT' },
            { title: 'La motricité', prof: 'Dougui', year: 2015, ext: 'PPTX', mb: '0.1', fid: '1LqTWAljX94jcpjt87zlO2n4j1_aG0z8B' },
          ] },
        { n: 8, title: 'Les réflexes médullaires', ext: P, mb: '7.9', fid: '1nllkH5rohbR1pf9WY6IE2asOVd4suDCX', year: 2024,
          versions: [
            { title: 'Les réflexes médullaires', year: 2023, mb: '10.5', fid: '1wWpluYJaYK0aGlZw2MsiIiM2V4loZc4Q' },
            { title: 'Les réflexes médullaires', prof: 'Dougui', year: 2009, ext: 'PPT', mb: '0.5', fid: '1BrKON2BnwUdGk3mnOJ-pIKwkBoyfDdB3' },
          ] },
        { n: 9, title: 'Le tonus musculaire et l’équilibre', ext: P, mb: '141.5', fid: '1NKbRMnygOlK20bITqDGl8pDcbqBWTE0A', year: 2024,
          versions: [
            { title: 'Le tonus musculaire', year: 2023, mb: '8.3', fid: '1pm7d_6IqQzMF5CMRcQRCyS6X8lSPCnAt' },
            { title: 'Le tonus musculaire', year: 2023, mb: '3.6', fid: '1gfyPT8JJbp9HUnEsSnBU3ReYVWs_Hs4e' },
            { title: 'Le tonus musculaire', prof: 'Dougui', ext: 'PPT', mb: '2.7', fid: '16IK61byNOIeketTsPYETepniaJJBZ0on' },
            { title: 'La posture et l’équilibre', year: 2023, mb: '7.4', fid: '1M8ptxoo6LzaviIMQwFIL823WNMxlYsAT' },
            { title: "L'équilibration", prof: 'Dougui', ext: 'PPT', mb: '0.9', fid: '1I5rOJRMTfQVwFxBki4MZjHyk0dKU8wH2' },
          ] },
        { n: 10, title: 'La marche', ext: P, mb: '0.5', fid: '1tOmzxkfosVI8iw1q7NVvgv3dXet2gTXS', year: 2021 },
        { n: 11, title: 'Le cervelet', ext: P, mb: '0.8', fid: '1NSj38kswyGviwFGPl-8j6LquKvkzmjvs', year: 2024,
          versions: [
            { title: 'Le cervelet', year: 2023, mb: '12.3', fid: '1WMyoOQI83ynoGCHGLsGNvr0CTRiQNL_f' },
            { title: 'Le cervelet', prof: 'Dougui', ext: 'PPT', mb: '0.7', fid: '1687P-i7HQwSCs_CQ9CFiFyCmgIejbhon' },
          ] },
        { n: 12, title: 'Les noyaux gris centraux', ext: P, mb: '17.6', fid: '1t9o1Z8TwsXx8SNz_MPm_5ySx8_AT5c08', year: 2024,
          versions: [
            { title: 'Les noyaux gris centraux', year: 2023, mb: '14.7', fid: '1GzmmcBGEwi8tOdwDvNQu9WrXiF9irKMG' },
            { title: 'Les noyaux gris centraux', prof: 'Dougui', ext: 'PPT', mb: '0.7', fid: '1vEVpT1m-hgGOa8Mpn1S6WZiKKRjMBsGh' },
          ] },
        { n: 13, title: 'Le contrôle cortical de la motricité', ext: P, mb: '4.0', fid: '1E8Ki2sUY2VpGr6HohPy8N-fc6hAIyfQK', year: 2024,
          versions: [
            { title: 'La motricité volontaire', year: 2023, mb: '7.7', fid: '16U3FgjOa1OM5E9TsRVsQH8YLDfMzlr1I' },
            { title: 'Le contrôle cortical', prof: 'Dougui', ext: 'PPT', mb: '0.8', fid: '1ihouplxf4a6ePkFWp9HnXBqTuF9yp9IY' },
            { title: 'Le contrôle cortical — polycopié détaillé', mb: '0.2', fid: '1uFyRgsxaQKiBcM6fqXdXu98J1Sm11dkv' },
          ] },
      ],
    },
    {
      title: 'Fonctions supérieures',
      subtitle: 'Cortex, mémoire, EEG, sommeil, stress',
      lectures: [
        { n: 14, title: 'Le cortex et les fonctions supérieures', ext: P, mb: '3.1', fid: '1QujwZgEWB9LoQ3QMDdpCVO8ZdaFBxcHh', year: 2024,
          versions: [
            { title: 'Les fonctions supérieures du cortex', year: 2023, mb: '3.6', fid: '1ISzrTx5THYmEV96CyWtOzsUyMp0IuhHt' },
            { title: 'Le cortex', prof: 'Dougui', year: 2020, ext: 'PPTX', mb: '2.0', fid: '1ORfyCFxf0lCYMT6lU3qzsjgpGuODQSZp' },
          ] },
        { n: 15, title: 'Les connexions thalamo-corticales', ext: P, mb: '2.9', fid: '1HoGi-fwhJOISuqQcOQAvCAC5KnUqBHD9', year: 2023 },
        { n: 16, title: 'La mémoire', ext: P, mb: '3.7', fid: '1pG1cRUe-c3o5dadEztvS1-9vxQ0gB_Xg', year: 2023,
          versions: [
            { title: 'La mémoire', prof: 'Dougui', year: 2020, ext: 'PPTX', mb: '0.9', fid: '1EsFY8S5WhKjZT6IjN3Ym_yR9Jz2BShB-' },
            { title: 'La mémoire — polycopié détaillé', year: 2014, mb: '0.4', fid: '1RFYR6qG1eQ45W6Yd9XfhVJfxzhAkh2o_' },
          ] },
        { n: 17, title: "L'électroencéphalogramme", ext: P, mb: '14.5', fid: '1LDOwKAGxld72OE4MCUFLSj2i1gZhsMJw', year: 2024,
          versions: [
            { title: "L'EEG — deuxième séance", year: 2024, mb: '57.7', fid: '1SapVOVH79S-pKJeCkPN8pvAcQiA8k3HV' },
            { title: "L'EEG", year: 2023, mb: '4.4', fid: '1zc0QgH7EuA-LF2PZNE6asqCsqekji29z' },
            { title: "L'EEG", prof: 'Dougui', year: 2020, ext: 'PPTX', mb: '4.3', fid: '15kZ6LjFzHPxBQgKa33n1DbK0MlC_xudK' },
          ] },
        { n: 18, title: 'La veille et le sommeil', ext: P, mb: '7.1', fid: '1_GWxLLlHKt4HOPgsxfBA1z8ZN0t8XGSA', year: 2024,
          versions: [
            { title: 'Le sommeil', year: 2023, mb: '18.8', fid: '13tooAfeOdYRj5V9oGs91bU4f0F1abKvP' },
            { title: 'Veille et sommeil', prof: 'Dougui', year: 2022, ext: 'PPTX', mb: '5.1', fid: '17dv2dnRO4Io7MYDhwjRTFp0O0_2nUpkm' },
            { title: 'Veille et sommeil — polycopié détaillé', year: 2015, mb: '0.5', fid: '1RMNREvusJ2tqBHe0HI5uCun0LZd8JX8q' },
          ] },
        { n: 19, title: 'La chronobiologie', ext: 'PPTX', mb: '3.7', fid: '1nEiOkg-403LADr4JRDXz33zLMmOJqSIg', prof: 'Dougui', year: 2020 },
        { n: 20, title: 'Le stress', ext: 'PPTX', mb: '3.6', fid: '1kAOy0gc6daceAmPloUAcY2qqf05v3nkr', prof: 'Dougui', year: 2020 },
      ],
    },
  ],

  sections: [
    {
      id: 'polys', where: 'archive', title: 'Polycopiés', icon: 'book',
      items: [
        { title: 'Polycopié complet — 2023–2024', ext: P, mb: '4.1', fid: '1UYHgouFReFuRzROkRPLXM8tfpQ_Tyl4a' },
        { title: 'Polycopié complet — 2023', ext: P, mb: '4.9', fid: '12_TSqpAljwSm-QZUspqy2guHNqpiz4vF' },
        { title: 'Polycopié complet — 2022', ext: P, mb: '4.1', fid: '1D9aCDBr2IkYNKlalCyTaBNu9UQ0XXi6G' },
        { title: 'Polycopié complet — 2021', ext: P, mb: '4.9', fid: '1cvlLCd32WWaKotZvAq1VWsxwAbqlKUOl' },
        { title: 'Polycopié complet — 2020', ext: P, mb: '2.6', fid: '12ozvjXICjNn7vSmaJK-ekfkExVMH6o8V' },
        { title: 'Polycopié complet — 2019', ext: P, mb: '4.5', fid: '1BzeC4ZnERZKjcUm6DFtqW70QDP0Vce3w' },
        { title: 'Polycopié complet — 2018', ext: P, mb: '6.3', fid: '1mTzSs--xsw8-P7a0SeltmwC3aEj3sNKI' },
        { title: 'Polycopié complet — 2017', ext: 'DOCX', mb: '10.8', fid: '1QAwiUB2WUhEnnjD9G0YyvbDmtLw_BlVh' },
        { title: 'Polycopié complet — 2015', ext: 'DOCX', mb: '2.5', fid: '1ewPsbSmdMc83puLtIdKQbfEVADo-KHH5' },
        { title: 'Polycopié — isolés de Ben Cheikh', ext: 'DOCX', mb: '1.6', fid: '1ejSYm94FKOR91xVXIu-yw2drielj4EXc' },
        { title: 'Polycopié complet — 2020', ext: 'DOCX', mb: '2.0', fid: '1H8_rKIgf3aEPnrptg41Cxp2e5D5OG5EV' },
      ],
    },
    {
      id: 'polys-det', where: 'archive', title: 'Polycopiés détaillés', icon: 'book',
      items: [
        { title: 'La motricité', ext: P, mb: '0.1', fid: '1ytzG7CO934jq6R9BfeX0IXFWwBpTHvs7' },
        { title: 'Le contrôle cortical', ext: P, mb: '0.2', fid: '1odSQ8MQsesVHqW_WRAt_eXJd8cW0RkhN' },
        { title: 'Le tonus musculaire', ext: P, mb: '0.2', fid: '1HlZjU1XGkbJzDRRdksbx0jLsKZTX_9qI' },
        { title: "L'équilibration", ext: P, mb: '0.1', fid: '1ROCDhHd4TLZM2FLy4tXwCY8rFI_i3s2u' },
        { title: 'Le cervelet', ext: P, mb: '0.1', fid: '10036C6Uf4_tKvTiOT5uPC2piBZiU8E01' },
        { title: 'Les noyaux gris centraux', ext: P, mb: '0.1', fid: '1UPYPhhiiCa-sek0UtV96UjOsGB-XASrk' },
        { title: "L'EEG", ext: P, mb: '0.3', fid: '1LEA-lQ7FHfQJch1TkoD4LxP3KvccHyWf' },
        { title: 'La motricité — polycopié', ext: 'DOCX', mb: '1.6', fid: '1Y5xIqr0xcPDMpp06-ngMPcSp3pBQrUrn' },
        { title: 'La moelle', ext: 'DOCX', mb: '0.0', fid: '1REGf0QM_NjGGF8tzJWyAmCvkqKHEn74T' },
        { title: 'Le stress', ext: 'DOCX', mb: '0.0', fid: '11AMdps-PEQrVy8WiMXt1jPsI-MFXrkUp' },
      ],
    },
    {
      id: 'resumes', where: 'notes', title: 'Résumés et corrections', icon: 'file',
      items: [
        { title: 'Corrections des examens — recueil', ext: P, mb: '27.1', fid: '1e1x7qRwREAxiaOS-haZaoj7fSekK99hO' },
        { title: 'Physiologie S2 — notes', ext: P, mb: '12.4', fid: '1Itqxo7XyrdLqNdmNmDUJv38bUut8-A9q' },
        { title: 'Corrections — recueil de Monastir', ext: P, mb: '1.0', fid: '1JQijoE3XR4QIVIOc6m72wmldTkfqRwzy' },
        { title: 'Correction — ED', ext: P, mb: '7.6', fid: '1O4vwmd6JFQEPXhdGFY57fn-CEk9M3ieU' },
        { title: 'Correction — ED fonctions supérieures', ext: P, mb: '0.8', fid: '1Bz3Fvaq9ue4i_GwB8H867nFujxSU-SE8' },
        { title: 'Résumé — physiologie S2', ext: P, mb: '6.4', fid: '1xhr62f0zX-kmTJP6SFkzNSL4_kAagpQt' },
        { title: 'Résumé — le sommeil', ext: P, mb: '2.1', fid: '1b3o0JHNSl8zEKuLxJDZFvFaqKifFQ6yS' },
        { title: 'Résumé — la vigilance', ext: P, mb: '0.7', fid: '1wsSBsO2HZuM4J1JKDLL2e2yEQfkhdAjo' },
        { title: "Résumé — l'EEG", ext: P, mb: '0.5', fid: '1UMqJUKIQEumTE60D2NUb8Yum4X1QeCLa' },
        { title: 'Correction — physiologie 2021', ext: 'DOCX', mb: '0.0', fid: '1mFZtMcy9IMvDtAQk19epAwUDiwjlZWx4' },
        { title: 'Correction — physiologie 2019', ext: 'DOCX', mb: '0.0', fid: '1MrhmCfSAR0Ui6sf5CBe_Ek61NgDjZGFC' },
      ],
    },
    {
      id: 'examens', where: 'quiz', title: 'Examens', icon: 'quiz',
      items: [
        { title: 'Session 2024', ext: P, mb: '6.3', fid: '1pilWU9lWU6DEVCUZOcrS6uvXiRMzerv5' },
        { title: 'Session 2024 (2)', ext: P, mb: '1.4', fid: '15aYtiUAkQP0bDmpJsqxef4LsqgKqtmZb' },
        { title: 'Session 2024 (photographiée)', ext: J, mb: '32.4', fid: '1oKYG6dYcHdmeef1G1Kj_4fMJYYl8Y45W',
          pages: ['1oKYG6dYcHdmeef1G1Kj_4fMJYYl8Y45W', '1dX4YLA3SC6h-6fVP82LT9HzzT3IkzqNG', '1gc1jDuPjTv2XCCpuQojZ11h4sgEWNg37', '1f9hzoqQZX5CsRjcY7fIus4MgYXo9T2gv', '1KtplYPBpyBja_yDvuGW7K1D0IauL8epJ', '1fVomkGWYUNtpg3FZFUucsJGU-P5jOpiC', '1YsDVwEAjiXhJXOj7l-zcvScRH9NaHh7c', '1Tw_GaKBXdws_D3lTYdXL5vTq8WOSKklo', '13jOHkQlPUyGg3guShUbZ2tPvgh1C3iKp', '1eHgeLoiSHinPJB5ncQbgqAqk1JITocJF'] },
        { title: 'Session 2022', ext: P, mb: '0.1', fid: '1fmqcQ5Y2sr_XMChxcs9EmHAgLmAYtuOe' },
        { title: 'Session 2021', ext: P, mb: '5.8', fid: '1IkQZTRCnOSuCPNFUQsk3LFuo__RmduFp', correction: '1O48hBqdjt2ofGhLtTQIbhF-xFpeKnFmj' },
        { title: 'Session 2019', ext: P, mb: '0.8', fid: '1eMCfROY4wj1Go3ZdeqYE3KLo1H50p3dg', correction: '1vGHXn4wCxSFtRXE35cx8EVOVKlLVp61G' },
        { title: 'Session 2018', ext: P, mb: '6.1', fid: '1SNQDrSgX3n4dCoDCLpTGioMd-IYKL_S2', correction: '1f9u0pw6VsIAbi-ikHJ0fvYa1CAm3aZ2o' },
        { title: 'Session 2017', ext: P, mb: '1.3', fid: '1eTKUjTI645TSt4ZNenCfm5awVDGPr7Yr' },
        { title: 'Session 2016', ext: P, mb: '0.5', fid: '1YQXhUCXKg3LsGqVfgXE9A5AJ1Lbtbb1z' },
        { title: 'Session 2015–2016', ext: P, mb: '0.9', fid: '1s1KPNo2UHSrdKYOsK6sh8mF7smBWfujA' },
        { title: 'Session 2015', ext: 'DOCX', mb: '0.0', fid: '140rg6hfeaZWoRXlQcmFZTusnJHPxr2Wo' },
        { title: 'Épreuve — PCEM2 S2', ext: P, mb: '1.3', fid: '1OkYGhkI6EPw-UiwhDsEqfr1hkH0y0Q1w' },
        { title: 'Rattrapage 2024', ext: P, mb: '2.2', fid: '1Ey7R2X7XNDvv6WyPOjhRLP8dtGYZwXHa' },
        { title: 'Rattrapage 2023', ext: P, mb: '2.6', fid: '1wxKB2onDkQlTAwUgvbgucn8hx-8qfDlS' },
        { title: 'Session complémentaire 2022', ext: P, mb: '0.9', fid: '1eNG8Byq0dTQlEveMmkIHt3pZcXd-k6N0' },
        { title: 'Rattrapage 2021', ext: P, mb: '0.5', fid: '1gQYDMLT1Y4w2mIZQCNU7NiT9O0JSPIRw' },
        { title: 'Rattrapage 2021 (photographié)', ext: J, mb: '0.6', fid: '1USWSyS1vdj6nCrZaNON08fpS8KrGGTVV',
          pages: ['1USWSyS1vdj6nCrZaNON08fpS8KrGGTVV', '1mqaU63j-xMq5BL5X_LVtiHlRxA7VOWNW', '1ZGKOrdfTIBav7fH4xq6hvY5w24Jbe1rd', '1Yx3xyLtsbHWlUjZuSXJ8FZcVZR1IKvto', '1K7RjJ-Ru_6fsr7KR6z6NgROSxC0Mx7sP', '1Wf8xqMxAwqdvRWHrgUpUJ_aGV2OixFRC', '101PGYXBjXtd2qGtmx9ZHpUhLZVEkTuTV', '18KwTG9vHOqrkjPdERprJ8qBs4wgC09S0', '17c0Y93rJKqpQoHxOnBYF9YdGkH69xPHT', '1nCMHcAZbp_8B9cz_NxdVyxbcUG4YS4u_'] },
        { title: 'Rattrapage 2019', ext: P, mb: '2.2', fid: '1aBOW_xT4EVtIKv7TTbXncQg6A8de9ia7' },
        { title: 'Rattrapage 2017', ext: P, mb: '14.6', fid: '16orVUkd6UQeew6uizhJzFiDtylOvcNDY' },
        { title: 'Rattrapage 2016', ext: P, mb: '4.4', fid: '1VFgTSR8f-Ej-ilNoPxvVUyFqK91BFPAF' },
        { title: 'Corrections (photographiées)', ext: J, mb: '1.1', fid: '1LyNaZhhBXFhKvhZS0DyK_ka6M9ekfKKd',
          pages: ['1LyNaZhhBXFhKvhZS0DyK_ka6M9ekfKKd', '13aLs6cX7dUYK5fxAPDk3M4S3H5HnWBOd', '1BZndE8ZnGB0RU1FajGqRQ0p23ved2NZI', '1LL6yl3ECA2_MiBLSlA-fcTrSLrSf53K0', '1EiZeRNo7AB2z89G4LTzoxBS_Zj8UNz7L', '1uGy0OOSA2rFIA5S7xPT4asY-hI8g4u_1', '1-4pvvIR-g6dfhq9c8BZt48OZNmAC0ea1', '1DY_QcU5qdakaRVcYMEQ4O01xfw5ZixjL', '1qLHlIGiN3DIhH86zmsOG7GecCzUrFN2o', '1smkRX6cv5JtXOgwbtgYksKVMibX_rm1Q', '1LTOqdmnecqdT90L4FtDIR2J1PFo5RRha'] },
        { title: 'Correction — examen de physiologie S2', ext: P, mb: '0.8', fid: '1tzF8UXuaZSN9lXB9F2SW6WFN27Yv8ULz' },
        { title: 'Correction — physiologie S2, version 2', ext: P, mb: '0.1', fid: '1_xsqJ_GWiHbfY6RTVVpVK94ATGF70bnE' },
      ],
    },
    {
      id: 'isoles', where: 'quiz', title: 'Isolés par chapitre', icon: 'quiz',
      items: [
        { title: 'Isolé — la somesthésie', ext: P, mb: '2.1', fid: '1VrD9mBdLtmTThaolSrbsyXmY5lQNShMv', correction: '1RkbPGcM0k52qEITgkwy6q9vJVj1XG848' },
        { title: 'Isolé — la douleur', ext: P, mb: '1.0', fid: '15jmOL-kasqT1f526XUdvL0n5-4Qs2jL5', correction: '1ItqjppdKkOn95_dmIFUzuYOR-y3PJSmx' },
        { title: 'Isolé — la vision et l’audition', ext: P, mb: '2.1', fid: '1a6WEmNbPBhYiFE7WPJ1440KTVZleq3OB', correction: '1XKLPHpvSh9x66tUFSzzJ6gQlQtWN_aDh' },
        { title: 'Isolé — l’audition (corrigé)', ext: P, mb: '2.4', fid: '1UYRdylCbfRSj3KREecXJa81K58oAC4qn' },
        { title: 'Isolé — le système sensoriel', ext: P, mb: '2.1', fid: '1F40zyRvbz6B2ZSy7GOZ0OrbQwhJJsLn1', correction: '11x-GGHl1hkUBz5Bss1-KH4irVtWDLQIf' },
        { title: 'Isolé — le système sensoriel (recueil)', ext: P, mb: '44.4', fid: '1n3Y3th7bK9fppHkYX9WOyslC81cHIrYE' },
        { title: 'Isolé — les réflexes médullaires', ext: P, mb: '1.2', fid: '1w6lzWDNZeaZJwpq1W3atSeqDsDYNmgAD', correction: '1-BchqYtk9rUZq1FIbTQxrO8TKMrquMJY' },
        { title: 'Isolé — le tonus musculaire', ext: P, mb: '0.8', fid: '1Q8c9BfXprJ2311NDJD9Sj46tTsEhOgNJ', correction: '1Go8A7aFmTLiJWzdHkwBHN36uYyOeZD3i' },
        { title: 'Isolé — l’équilibration', ext: P, mb: '1.5', fid: '1iV7TvuiYJ5-Vr361_2_sGSOGNL4OhPeN', correction: '1GDYyeTHFrcXD354GHzY-qTg90xk1Mpp-' },
        { title: 'Isolé — le cervelet', ext: P, mb: '0.5', fid: '1TpS5pTmIenhi-2B_2kjYhF0V2FmDwaer', correction: '1UAXPfDjis8tijOa-q2LuOs8ox-c4llZD' },
        { title: 'Isolé — les noyaux gris centraux', ext: P, mb: '0.7', fid: '1mM0PAgDHJrv69V_7qul47kpvD3DkXas2', correction: '1XN65SXOlVTOqutyQhg0oANX7dr3bKAAE' },
        { title: 'Isolé — le contrôle cortical de la motricité', ext: P, mb: '1.0', fid: '1uLd1d2feX67cB1_6M7NT8X5URKfZPlmZ', correction: '14R2ShMMYn2R8CmG6H_9uczejvQM0H3Oi' },
        { title: 'Isolé — la motricité', ext: P, mb: '2.9', fid: '13cGXJ_s2b_boj2i_iGqGGq8T0kNvW4yM' },
        { title: 'Isolé — la motricité (recueil)', ext: P, mb: '29.8', fid: '17aRhyVe8qvUrDu1hTcYp1CTclahTuptO' },
        { title: 'Isolé — le néocortex', ext: P, mb: '1.5', fid: '1m9feBbvmoIhFNnNF8VRR8IOUAAhZOXL6', correction: '1DqNV5qYr6CACFULoImKYzRvThv9CpL2S' },
        { title: 'Isolé — EEG, mémoire et connexions thalamiques', ext: P, mb: '1.5', fid: '1lPTBs3NH-e4cveuxVOZycwjcFC5jE_nz', correction: '1Iq5FxVcwthAJuIbtcs4mm_KdG1FqxAez' },
        { title: 'Isolé — la mémoire (corrigé)', ext: P, mb: '2.9', fid: '1FwTzb21h-K8PSDn2QsJkuSBpfCkfNXMC' },
        { title: 'Isolé — le sommeil', ext: P, mb: '1.4', fid: '1OOL-cBa_B17EiDjeN9a1_i5ulIGXaaTI', correction: '1U4BdE_Eh3PU2dlFodc8ACJ2kBpQ2mEit' },
        { title: 'Isolé — les fonctions supérieures', ext: P, mb: '2.5', fid: '15B_8abplXCkidoc-v8ylhN3FTqppbmPD' },
        { title: 'Isolé — les fonctions supérieures (recueil)', ext: P, mb: '27.8', fid: '148eBf_-AsXoaM86ca4siO-2rbt43qpXN' },
        { title: 'Isolé — la circulation', ext: P, mb: '1.9', fid: '1OcYTpsvETmeFkW7f6AlOxxkSErFal1AE' },
        { title: 'Isolé — la digestion', ext: P, mb: '1.8', fid: '1sgNGq5p4X1P1h-E4obtW2Bi1BYeAH8Z9' },
        { title: 'Isolés — recueil', ext: P, mb: '4.2', fid: '1_5x-FfSyID-QK8sGv3jz-liXuPAHJGGB' },
        { title: 'Isolés — correction 2024', ext: P, mb: '4.1', fid: '1NgLuFakHWjxfbfZ61-97eFZmvMPCGNkr' },
        { title: 'Isolés — correction', ext: P, mb: '4.8', fid: '1fkwTmasKozt43TDsXbvnI32CqWWPCVCa' },
        { title: 'Isolés — correction (2)', ext: P, mb: '1.5', fid: '1dCqf28N3Ni2ZDXTm1Us9EQAcU7cVlWOM' },
        { title: 'Isolés — questions choisies', ext: P, mb: '1.1', fid: '1PaJH_-Hree4q1Igu-hl6ulf3LRTECah3' },
      ],
    },
    {
      id: 'qcm-bc', where: 'quiz', title: 'QCM — Pr Ben Cheikh', icon: 'quiz',
      items: [
        { title: 'QCM — physiologie S2', ext: P, mb: '16.5', fid: '1bH961cwXagXEndNk1sbUYEO-zVuuh1XM' },
        { title: 'QCM 2024', ext: P, mb: '1.0', fid: '1AAOptRWWRMBmojA_u3fBpaIZk29FjLxJ' },
        { title: 'QCM 1', ext: P, mb: '0.5', fid: '1yQEtRsOEVPOlBr7RzZNeIyCS0OPW5SvK' },
        { title: 'QCM — recueil', ext: P, mb: '0.2', fid: '16ft5ft2s7jekOTjeRWggo-6-Eq-U0rt-' },
        { title: 'ED — physiologie digestive', ext: P, mb: '0.6', fid: '18t4YkGmsrHO3OEKyrOYtP00dv-AftYt0' },
        { title: 'ED — physiologie digestive 2021', ext: P, mb: '0.1', fid: '11OSFIZ9QDDv2qjqh_ciPAmCMQ9WLvy7K' },
        { title: 'Correction — ED', ext: 'PPTX', mb: '0.1', fid: '1oIzIVvg0bVwZImQ_C5G707OyGHJ6-5Ck' },
        { title: 'QCR — la vision', ext: 'DOC', mb: '0.0', fid: '126rtWA2YNY5purd-xpn9ZRfmdOCgJLcL' },
        { title: 'QCM photographiés — 43 pages', ext: J, mb: '2.8', fid: '18eZ972Kb9Tfv1ADjEvh7KFiKJ5t5DaXl',
          pages: ['18eZ972Kb9Tfv1ADjEvh7KFiKJ5t5DaXl', '1Fyw0E8Z5IZDraERQPjwC01qSSgA3NWRZ', '1HtaBvzWU0PWDoZEv9xO9lYFRjfhg535F', '1uMU5ua_AmvXmZHUjnO_adbq9lBQLzSaW', '1ftgP_eqlHWKQoIgwIL9VIFU4CA_rB9V-', '1cm42jQaHixRBWnVmo28fyeOEvIe41FsR', '1Vdh-arCRuTSrYG4Iv4WOEHdBoqzwUygU', '1Ub97AS7pqNxw4L37g3yf9rMwq3J2ZsD5', '1_4lbByuMY_KXPs_kIG88BWXjVsLDuAj9', '1QxWs49o6Om8VGbwh5h69bCrIpJ5dgazT', '1uZtea8arDQUKsmQ8kIfTzge2rj6XIr8D', '1ZSDhWaheyOg5emagxbpTk1JbrZn7XKyg', '1izNVoYuEgcmR915ZHfV54dP1VdVPdHGR', '1BH1lohv4amItK0TWacmCV6v6vLw4DwuU', '1Pbabz5NadxmnmPfgHvfIzbhNDnAr4jXL', '18GBxBvDEEafxNAQJ0xNfk4antLsKMU-Q', '1dOsjyp2RNVGgsk-6oLBOGWbSS8DpMqu9', '12pcnviFvGt6rdHIWb9zHvIH9NEghOyyb', '1_uWtRY-SQZDmnRcFylwbCIYUrf2B-g86', '1xKiV1wiHpD0tw8WWHwI2rbM5yJ8TSTpc', '1oGZ0EiZc3T6tPYHWS_cxfVIvpz9rmKlT', '1060zebV5CzUnyS4dsQ1iNPHUENxZ0K0y', '1I9Tz-ElT_TAHnRt7x9PJH7IOIUfWG4ZI', '1kLw3gAow1raqUrnnZZ4Cc28h_RLjjQaB', '1cPKdo4BZ9Sdm-ZW-J-tlKxHDdPyeG6TJ', '1SdsD3JxEvckDJ7fTVrz0xN3KQ_w_tT9m', '1I8lRFKLPLo7Ad_tGuKAStgHt27RLgun2', '1ady4S0Gys-S1mPZlFOyiYu3luXH9HmwV', '1eoucSwRdiUaTV7PM3ZdWmN7Wig5YR4hr', '1QU0a4AENDSlGQyKVR1XWzPRD-eBXdgSP', '1D3swz0qwZWVgNH_A7O7hV8zU-t55z_6F', '1wd2rSJrtTDqkY4is1MCP_R-17Q2m8mtU', '1Je08RcA24flLEnLvyT91GX0GX3rPRvWk', '1s0tfZva0-tC_JEHSSUE7U1J1KAVhHpIR', '1WQEpgjaefiRv0o9s5r6wEau0m7hKA2fW', '1KXt7afiu8CctISHr6Fl5Tp8vz80O2MRD', '16O-h_KVpks6CeSQACXP7TIT05f7LeyBG', '1nC52LqfUAus14PnZfXSHSrLs0xJP3Ble', '1FO_X3uIGyez3xYqCg86WMzQRQ4JhRa-_', '1Ly-XYOdNGBQsSAF06ikIbI__Umrz-fyG', '1IOmT4Z6LBntKiArsFeV48A2DWAWnIxq2', '1JYtl3GaqeuYg4ZQfsih_5VRBgvlFpv5u', '10VOvUnL1jeAHmcN0AkhOKDOdAk3D_xqN'] },
      ],
    },
    {
      id: 'ed', where: 'quiz', title: 'ED et anciens examens', icon: 'quiz',
      items: [
        { title: 'ED 1 — les systèmes sensoriels', ext: 'DOCX', mb: '0.0', fid: '1oMP12q-CWDhSG0o6WMaZUEhXD4yBaq-8' },
        { title: 'ED — la somesthésie, questions', ext: 'DOCX', mb: '0.0', fid: '1NO4aAElo09rORxzClHDZQWU5Bjq_jfmf' },
        { title: 'ED — somesthésie et douleur, questions', ext: 'DOCX', mb: '0.0', fid: '1vWEqluNoQMj16FrAqoqrF2mX0bB14PDc' },
        { title: 'ED — vision et audition, questions', ext: 'DOCX', mb: '0.0', fid: '1dAMqwGFcEUjexR8HhW6K1FG_hc1t9qny' },
        { title: 'ED — neurophysiologie, questions', ext: 'DOCX', mb: '0.0', fid: '1NsvSDsaIMXXF_DEQaev8DC1R87N70K5c' },
        { title: 'ED — neurophysiologie, questions 2013', ext: 'DOCX', mb: '0.0', fid: '1QZ5-AlRXqWMR-DpH8HlJ_dE40ajrDW-h' },
        { title: 'ED — neurophysiologie, questions 2010', ext: 'DOC', mb: '0.1', fid: '1OO6gL1yGB5EVRogIXZTl-_HvPSkAPWJS' },
        { title: 'ED 2 — 2011, complet', ext: 'DOCX', mb: '0.0', fid: '1moxZJYp7pSpej1tgxbqWmK5hCSZK9iiX' },
        { title: 'ED 2 — 2014', ext: 'DOCX', mb: '0.0', fid: '1XtyDtwlNvUtfuXCSlTUwjaB9yC5NHlTN' },
        { title: 'ED 2 — 2015', ext: 'DOCX', mb: '0.0', fid: '1A0agHLGlBk4yQsrN6TRaKTH4XUiakXBH' },
        { title: 'ED — rythmes et stress', ext: 'DOCX', mb: '0.0', fid: '1t-QnKg0YTeozHIE0D5byi9W8dntzlTgH' },
        { title: 'Examen 2015 — PCEM2 S2', ext: 'DOCX', mb: '0.0', fid: '1TA8egEhADdYDBBzgPukp6K-m6a7Rz85h' },
        { title: 'Examen 2015 — réponses', ext: 'DOCX', mb: '0.0', fid: '1ymtjAJ0RUKM3VNcygDV-5NfsBg4aF7yX' },
        { title: 'Rattrapage 2015', ext: 'DOCX', mb: '0.0', fid: '1bEUkTFhza12G2yCuacnCftBXzTWuUKr9', correction: '1vYSZcxRa3ANqT8Grzk-VzZZXMSHazyl9' },
        { title: 'Rattrapage 2015 — non grévistes', ext: 'DOCX', mb: '0.0', fid: '1b540f05ynatRuNKn3HUwpF00wPAzaRBA' },
        { title: 'Examen 2015 — Dougui, réponses', ext: 'DOCX', mb: '0.0', fid: '1cY_0-DOEs0Eq5uQRh6Xl2neh-WvZFveg' },
        { title: 'Examen 2014 — principal', ext: 'DOCX', mb: '0.0', fid: '1oCV1Zc38leA2eYPYN-br0zzj5o1vd45e', correction: '1Bt5uScuOJY49CT7k7ho7RsgW8ZX1Qbxi' },
        { title: 'Rattrapage 2014', ext: 'DOCX', mb: '0.0', fid: '1DjuqvIUeKr9GXJ2UBdvCZ9wpYAiVSvtE', correction: '1yvwbKcNLyheEh7G3Npkno2-5m2F0AYPz' },
        { title: 'Examen 2013 — Dougui', ext: 'DOCX', mb: '0.0', fid: '1FCuvykTETjUIHV3W9slhU3Y4A6Dkcn2z' },
        { title: 'Examen 2012–2013 — juin', ext: 'DOC', mb: '0.4', fid: '1Ia4O3d7LQyttb9o7WJYJpOVxvSPUHhyA' },
        { title: 'Examen 2012–2013 — septembre, corrigé', ext: 'DOCX', mb: '0.0', fid: '1n5-7k7c961a2kP1fT1lwn7RXdlWrGHy4' },
        { title: 'Examen 2011–2012 — septembre, corrigé', ext: 'DOCX', mb: '0.0', fid: '1ADq_nsf6iCsA4z3OJFlAW2jVWuBtHSW7' },
        { title: 'Examen 2010 — principal', ext: 'DOC', mb: '0.0', fid: '1-nj75Uo7STQnpqorOJ9KDMKUV_ENQ3QC' },
        { title: 'Rattrapage 2010', ext: 'DOC', mb: '0.0', fid: '1D1aTWO2Mx-_RWzGnuYoiTcsRuezVQioH' },
        { title: 'Examen 2009 — principal', ext: 'DOC', mb: '0.0', fid: '1zZuNNanOtDvrVvBHD_QeJucBATDgU0PS' },
        { title: 'Rattrapage 2009', ext: 'DOC', mb: '0.0', fid: '16tikF9vEFb9FNRVIYNRbrCnxC4rcFn37' },
        { title: 'Questions anciennes — PCEM2', ext: 'DOCX', mb: '0.0', fid: '1k5yUzcd_hBluKhXOkTVOAbdv8XwEv2Lk' },
        { title: 'QCM — Dougui', ext: P, mb: '1.2', fid: '1-K7-schPcot8kWNu6HgrRWzdOTQTj60D' },
        { title: 'QCM — Dougui, corrigés', ext: P, mb: '0.2', fid: '18OHbaIN7m4JKMoe4p6iRE_ueJOmc-12j' },
        { title: 'QCM corrigés', ext: P, mb: '0.2', fid: '1vbYKulbBuGpT7i6ZJ4PwVUj0Offy9CSs' },
        { title: 'ED — la somesthésie 2014', ext: 'DOCX', mb: '0.0', fid: '1aw0-FwGU6XfdQ_7RPNc0A2yan9sGdRwR' },
        { title: 'ED — la somesthésie 2009', ext: 'DOC', mb: '0.1', fid: '15_efs8GFbN3p2jmLviAto4lzL_rLxnvY' },
        { title: 'ED — la somesthésie', ext: 'DOC', mb: '0.1', fid: '1sS89lR0W19vZjmmPOvjw3BlfHfznB5ON' },
        { title: 'ED — la somesthésie, diapositives', ext: 'PPT', mb: '0.5', fid: '15zlPFuHklY0p5ZSNRmI0bYcC2_oFiZhS' },
        { title: 'ED — neurophysiologie 2013, complet', ext: 'DOCX', mb: '0.0', fid: '1mSxy6M_hCY0op18xv2BAvBN1eOHe7JgI' },
        { title: 'ED — vision et audition 2015', ext: 'DOCX', mb: '0.0', fid: '1Ng5PvkRl4yx_r4ta531MqsQiH1bdLHmg' },
        { title: 'Devoir de neurophysiologie', ext: 'DOCX', mb: '0.0', fid: '1qVtC7J8VFuzefW5KH-yTawg7Z93tcK_j' },
      ],
    },
    {
      id: 'djibouti', where: 'quiz', title: 'Examens — Djibouti', icon: 'quiz',
      items: [
        { title: 'Session 2015 — principal', ext: 'DOCX', mb: '0.0', fid: '1xFqn_EIZ0h9ZWJND3C_BicIXBwUuJR3x' },
        { title: 'Rattrapage 2015', ext: 'DOCX', mb: '0.0', fid: '1zxdbR3Vt8RYm_NbF8jjU496MqyElPTau' },
        { title: 'Rattrapage 2014', ext: 'DOCX', mb: '0.0', fid: '1XZ2Ng7xUCGGSQwWGl73V90Yb748YK4IJ', correction: '13zNDXVZOjIxAMP5AZCtME5A6aDiLvVBQ' },
        { title: 'Session 2013 — principal', ext: 'DOCX', mb: '0.0', fid: '1bhBalDezGCcYOfY-c6RsuMHySO9koBXM', correction: '1TFvS1Fd0evbi5QVGhpLc4s87UHSyk40g' },
        { title: 'Rattrapage 2013', ext: 'DOCX', mb: '0.0', fid: '1-nHBa322rfM5i_VP6a3xExnJuWdxAOw1', correction: '1YIu5a0AiCAOwxlZYIdkcdbZLgs6qDnDQ' },
        { title: 'Rattrapage 2013 (2)', ext: 'DOCX', mb: '0.0', fid: '1XC-fVeTT72ZSU1UgOouMjTw4nxUm0JvC' },
        { title: 'Session 2012', ext: 'DOCX', mb: '0.0', fid: '17My8mq-rhtAq8znA08hkeT0Py6iGizLo' },
        { title: 'Session 2011 — principal', ext: 'DOC', mb: '0.1', fid: '1AND7JYwUND_t8MC4T3HNSRaQ8jsVK3Yp', correction: '1RA1Us8Laj0i8I2jE5jUX8BIjwAaEsDFH' },
        { title: 'Session 2011', ext: 'DOC', mb: '0.0', fid: '1MP2Wxy8QKg14iStya-vcY0rl5_C63F5y' },
        { title: 'Session 2010 — principal', ext: 'DOC', mb: '0.1', fid: '1VzZWlo4leZAB8mBSPIMkXcDE5YyoupXi', correction: '16qdoRk8q_Y0AIGbNUQ09GaJHuEjTDIt0' },
        { title: 'Examen Tabka 2013', ext: 'DOCX', mb: '0.0', fid: '1Vlsj-OLKvOHp3pr0sRAoA79WOIq-U4Lv' },
        { title: 'QCM — Ben Cheikh, Monastir', ext: J, mb: '0.2', fid: '1-Jo5p5xJB8UaGZ8-JJPcAXtJdKLblMyx',
          pages: ['1-Jo5p5xJB8UaGZ8-JJPcAXtJdKLblMyx', '12kd6Tfwny8lZ8A48N006UKO2nZ6Qa_4s', '1nuD63aCOI0T9qkjBFOMzH-PhR7jt99uO', '1UjM31Jf6im0lUnqUI4h5jpSIgkOHWbDq', '10RowBdJD09i01P3GuueX7X6vvc68CS99', '1aUkbEmX3-92j_w1TXtNLEdbiGrdUDxM_', '1ITmL4t7i8KCc8LcIL-6RioF1gGKa_yK3', '1S-5ZDxALdQ-VT-XR790potGsPsPJpcGF', '1y6DOFEkMF27y0GZJCoAHIHWwRQ_caywg', '1usIdfHiy5LHd28WwkTyGCjSGILRaymXX'] },
      ],
    },
  ],
};
