// French names for the whole body, where no model had named them yet.
//
// The regional bundles (bundles.js) name their structures by hand, and those
// names win: they were checked against a lecture. Z-Anatomy's own French
// definitions name a thousand more. This is the rest — written by hand, in
// the international nomenclature the app already uses (ulna, scapula,
// fibulaire), with the older French term in brackets where a teacher still
// says it.
//
// Keyed by the English name in the Z-Anatomy files, without the side.
// Read by scripts/carve-body.mjs only; nothing here reaches a phone except
// through the manifests that script writes.

export const NAMES = {
  // ---------------------------------------------------------------- squelette
  'Parietal bone': 'Os pariétal',
  'Sinus of frontal bone': 'Sinus frontal',
  'Frontal bone': 'Os frontal',
  'Sinus of sphenoid bone': 'Sinus sphénoïdal',
  'Sphenoid bone': 'Os sphénoïde',
  'Temporal bone': 'Os temporal',
  'Ethmoid bone': 'Os ethmoïde',
  'Inferior nasal concha bone': 'Cornet nasal inférieur',
  'Lacrimal bone': 'Os lacrymal',
  'Nasal bone': 'Os nasal',
  'Maxilla': 'Maxillaire',
  'Palatine bone': 'Os palatin',
  'Zygomatic bone': 'Os zygomatique',
  'Malleus': 'Malléus (marteau)',
  'Incus': 'Incus (enclume)',
  'Stapes': 'Stapès (étrier)',
  'Upper medial incisor': 'Incisive centrale supérieure',
  'Upper lateral incisor': 'Incisive latérale supérieure',
  'Upper canine': 'Canine supérieure',
  'Lower medial incisor': 'Incisive centrale inférieure',
  'Lower lateral incisor': 'Incisive latérale inférieure',
  'Lower canine': 'Canine inférieure',
  'Upper first premolar': 'Première prémolaire supérieure',
  'Upper second premolar': 'Deuxième prémolaire supérieure',
  'Upper first molar tooth': 'Première molaire supérieure',
  'Upper second molar tooth': 'Deuxième molaire supérieure',
  'Lower first premolar': 'Première prémolaire inférieure',
  'Lower second premolar': 'Deuxième prémolaire inférieure',
  'Lower first molar tooth': 'Première molaire inférieure',
  'Lower second molar tooth': 'Deuxième molaire inférieure',
  'Major alar cartilage': 'Grand cartilage alaire',
  'Lateral process of nasal septal cartilage': 'Processus latéral du cartilage septal',
  'Nasal septal cartilage': 'Cartilage du septum nasal',
  'Sesamoid bones of foot': 'Os sésamoïdes du pied',
  'Vomer': 'Vomer',
  'Posterior cells of ethmoid bone': 'Cellules ethmoïdales postérieures',
  'Middle cells of ethmoid bone': 'Cellules ethmoïdales moyennes',
  'Anterior cells of ethmoid bone': 'Cellules ethmoïdales antérieures',

  // ----------------------------------------------------------------- viscères
  'Uvula of palate': 'Uvule palatine (luette)',
  'Accessory parotid gland': 'Glande parotide accessoire',
  'Parotid duct': 'Conduit parotidien (canal de Sténon)',
  'Submandibular duct': 'Conduit submandibulaire (canal de Wharton)',
  'Free taenia': 'Ténia libre',
  'Mesocolic taenia': 'Ténia mésocolique',
  'Omental taenia': 'Ténia omental',
  'Bile duct': 'Conduit cholédoque',
  'Epiglottis': 'Épiglotte',
  'Superior segmental bronchus of right lung (BVI)': 'Bronche segmentaire supérieure du poumon droit (BVI)',
  'Lateral segmental bronchus of right lung (BIV)': 'Bronche segmentaire latérale du poumon droit (BIV)',
  'Posterior basal segmental bronchus of right lung (BX)': 'Bronche segmentaire basale postérieure du poumon droit (BX)',
  'Medial basal segmental bronchus of right lung (BVII)': 'Bronche segmentaire basale médiale du poumon droit (BVII)',
  'Lateral basal segmental bronchus of right lung (BIX)': 'Bronche segmentaire basale latérale du poumon droit (BIX)',
  'Anterior basal segmental bronchus of right lung (BVIII)': 'Bronche segmentaire basale antérieure du poumon droit (BVIII)',
  'Apicoposterior segmental bronchus of left lung (BI+BII)': 'Bronche segmentaire apico-postérieure du poumon gauche (BI+BII)',
  'Anterior segmental bronchus of left lung (BIII)': 'Bronche segmentaire antérieure du poumon gauche (BIII)',
  'Superior lingular segmental bronchus of left lung (BIV)': 'Bronche lingulaire supérieure du poumon gauche (BIV)',
  'Inferior lingular segmental bronchus of left lung (BV)': 'Bronche lingulaire inférieure du poumon gauche (BV)',
  'Superior segmental bronchus of left lung (BVI)': 'Bronche segmentaire supérieure du poumon gauche (BVI)',
  'Medial basal segmental bronchus of left lung (BVII)': 'Bronche segmentaire basale médiale du poumon gauche (BVII)',
  'Anterior basal segmental bronchus of left lung (BVIII)': 'Bronche segmentaire basale antérieure du poumon gauche (BVIII)',
  'Lateral basal segmental bronchus of left lung (BIX)': 'Bronche segmentaire basale latérale du poumon gauche (BIX)',
  'Anterior segmental bronchus of right lung (BIII)': 'Bronche segmentaire antérieure du poumon droit (BIII)',
  'Apical segmental bronchus of right lung (BI)': 'Bronche segmentaire apicale du poumon droit (BI)',
  'Posterior segmental bronchus of right lung (BII)': 'Bronche segmentaire postérieure du poumon droit (BII)',
  'Medial segmental bronchus of right lung (BV)': 'Bronche segmentaire médiale du poumon droit (BV)',
  'Posterior basal segmental bronchus of left lung (BX)': 'Bronche segmentaire basale postérieure du poumon gauche (BX)',
  'Anteromedial basal segmental bronchus of left lung': 'Bronche segmentaire basale antéro-médiale du poumon gauche',
  'Middle lobar bronchus': 'Bronche lobaire moyenne',
  'Intermediate bronchus': 'Bronche intermédiaire',
  'Urethra': 'Urètre',
  'Mesocolon': 'Mésocôlon',
  'Meso-appendix': 'Méso-appendice',
  'Adenohypophysis': 'Adénohypophyse',
  'Neurohypophysis': 'Neurohypophyse',
  'Inferior parathyroid gland': 'Glande parathyroïde inférieure',
  'Superior parathyroid gland': 'Glande parathyroïde supérieure',
  'Oropharynx': 'Oropharynx',
  'Nasopharynx': 'Nasopharynx (rhinopharynx)',
  'Mucosa of nasal cavity': 'Muqueuse de la cavité nasale',
  'Laryngopharynx': 'Laryngopharynx (hypopharynx)',
  'Soft palate': 'Voile du palais (palais mou)',
  // Organes des sens, rangés par Z-Anatomy avec le système nerveux.
  'Lacrimal gland': 'Glande lacrymale',
  'Ampulla of lacrimal canaliculus': 'Ampoule du canalicule lacrymal',
  'Lacrimal canaliculus': 'Canalicule lacrymal',
  'Lacrimal sac': 'Sac lacrymal',
  'Nasolacrimal duct': 'Conduit lacrymo-nasal',
  'Suspensory ligament of eyeball': 'Ligament suspenseur du bulbe de l’œil',
  'Tympanic membrane': 'Membrane du tympan',
  'Vestibule': 'Vestibule de l’oreille interne',
  'Cochlea': 'Cochlée',
  'Auditory tube': 'Trompe auditive (d’Eustache)',
  'Zonular fibres': 'Fibres zonulaires',
  'Vitreous body': 'Corps vitré',
  'Retina': 'Rétine',
  'Sclera': 'Sclère',
  'Posterior segment of eyeball': 'Segment postérieur du bulbe de l’œil',
  'Lens': 'Cristallin',
  'Iris': 'Iris',
  'Cornea': 'Cornée',
  'Anterior segment of eyeball': 'Segment antérieur du bulbe de l’œil',
  'Anterior chamber of eyeball': 'Chambre antérieure de l’œil',

  // ------------------------------------------------------------------ muscles
  'Common tendinous ring': 'Anneau tendineux commun (de Zinn)',
  'Inferior tarsus': 'Tarse inférieur',
  'Superior tarsus': 'Tarse supérieur',
  'Trochlea of superior oblique muscle': 'Trochlée du muscle oblique supérieur',
  'Temporoparietalis muscle': 'Muscle temporo-pariétal',
  'Hyoglossus muscle': 'Muscle hyoglosse',
  'Sternocleidomastoid muscle': 'Muscle sterno-cléido-mastoïdien',
  'Intermediate tendon of digastric muscle': 'Tendon intermédiaire du muscle digastrique',
  'Anterior belly of digastric muscle': 'Ventre antérieur du muscle digastrique',
  'Posterior belly of digastric muscle': 'Ventre postérieur du muscle digastrique',
  'Mylohyoid muscle': 'Muscle mylo-hyoïdien',
  'Stylohyoid muscle': 'Muscle stylo-hyoïdien',
  'Geniohyoid muscle': 'Muscle génio-hyoïdien',
  'Sternohyoid muscle': 'Muscle sterno-hyoïdien',
  'Sternothyroid muscle': 'Muscle sterno-thyroïdien',
  'Thyrohyoid muscle': 'Muscle thyro-hyoïdien',
  'Stylopharyngeus muscle': 'Muscle stylo-pharyngien',
  'Oblique part of cricothyroid muscle': 'Partie oblique du muscle crico-thyroïdien',
  'Straight part of cricothyroid muscle': 'Partie droite du muscle crico-thyroïdien',
  'External part of thyro-arytenoid muscle': 'Partie externe du muscle thyro-aryténoïdien',
  'Ary-epiglottic part of oblique arytenoid muscle': 'Partie ary-épiglottique du muscle aryténoïdien oblique',
  'Thyro-epiglottic part of thyro-arytenoid muscle': 'Partie thyro-épiglottique du muscle thyro-aryténoïdien',
  'Platysma': 'Platysma',
  'Iliocostalis lumborum muscle': 'Muscle ilio-costal des lombes',
  'Iliocostalis thoracis muscle': 'Muscle ilio-costal du thorax',
  'Iliocostalis colli muscle': 'Muscle ilio-costal du cou',
  'Longissimus thoracis muscle': 'Muscle longissimus du thorax',
  'Longissimus capitis muscle': 'Muscle longissimus de la tête',
  'Longissimus colli muscle': 'Muscle longissimus du cou',
  'Spinalis capitis muscle': 'Muscle épineux de la tête',
  'Spinalis colli muscle': 'Muscle épineux du cou',
  'Spinalis thoracis muscle': 'Muscle épineux du thorax',
  'Multifidus colli muscle': 'Muscle multifide du cou',
  'Multifidus thoracis muscle': 'Muscle multifide du thorax',
  'Multifidus lumborum muscle': 'Muscle multifide des lombes',
  'Semispinalis thoracis muscle': 'Muscle semi-épineux du thorax',
  'Semispinalis colli muscle': 'Muscle semi-épineux du cou',
  'Interspinales colli muscles': 'Muscles interépineux du cou',
  'Interspinales thoracis muscles': 'Muscles interépineux du thorax',
  'Interspinales lumborum muscles': 'Muscles interépineux des lombes',
  'Dorsal parts of lateral intertransversarii lumborum muscles': 'Parties dorsales des muscles intertransversaires latéraux des lombes',
  'Ventral parts of lateral intertransversarii lumborum muscles': 'Parties ventrales des muscles intertransversaires latéraux des lombes',
  'Serratus posterior inferior muscle': 'Muscle dentelé postérieur et inférieur',
  'Serratus posterior superior muscle': 'Muscle dentelé postérieur et supérieur',
  'Abdominal part of pectoralis major muscle': 'Partie abdominale du muscle grand pectoral',
  'Levatores longi costarum': 'Muscles longs élévateurs des côtes',
  'Levatores breves costarum': 'Muscles courts élévateurs des côtes',
  'Transversus thoracis muscle': 'Muscle transverse du thorax',
  'Iliococcygeus muscle': 'Muscle ilio-coccygien',
  'Pubo-analis muscle': 'Muscle pubo-anal',
  'Pubococcygeus muscle': 'Muscle pubo-coccygien',
  'Deep head of pronator teres': 'Chef profond du muscle rond pronateur',
  'Ulnar head of flexor carpi ulnaris': 'Chef ulnaire du muscle fléchisseur ulnaire du carpe',
  'Radial head of flexor digitorum superficialis': 'Chef radial du muscle fléchisseur superficiel des doigts',
  'Ulnar head of extensor carpi ulnaris': 'Chef ulnaire du muscle extenseur ulnaire du carpe',
  'Extensor carpi radialis longus': 'Muscle long extenseur radial du carpe',
  'Superficial head of flexor pollicis brevis': 'Chef superficiel du muscle court fléchisseur du pouce',
  'Deep head of flexor pollicis brevis': 'Chef profond du muscle court fléchisseur du pouce',
  'Oblique head of adductor pollicis': 'Chef oblique du muscle adducteur du pouce',
  'Transverse head of adductor pollicis': 'Chef transverse du muscle adducteur du pouce',
  'Adductor minimus': 'Muscle petit adducteur (adductor minimus)',
  'Tendon of extensor digitorum longus': 'Tendon du muscle long extenseur des orteils',
  'Calcaneal tendon': 'Tendon calcanéen (d’Achille)',
  'Medial head of flexor hallucis brevis': 'Chef médial du muscle court fléchisseur de l’hallux',
  'Lateral head of flexor hallucis brevis': 'Chef latéral du muscle court fléchisseur de l’hallux',
  'Oblique head of adductor hallucis': 'Chef oblique du muscle adducteur de l’hallux',
  'Transverse head of adductor hallucis': 'Chef transverse du muscle adducteur de l’hallux',
  'Extensor hallucis brevis': 'Muscle court extenseur de l’hallux',
  'Flexor digiti minimi of foot': 'Muscle court fléchisseur du petit orteil',
  'Opponens digiti minimi muscle of foot': 'Muscle opposant du petit orteil',
  'Iliotibial tract': 'Tractus ilio-tibial',
  'Tendinous arch of levator ani': 'Arc tendineux du muscle élévateur de l’anus',
  'Iliopectineal arch': 'Arcade ilio-pectinée',
  // Fascias, rétinaculums et septums: their own layer, off at first, because
  // a fascia drawn over a limb is a sleeve that hides every muscle under it.
  'Superficial layer of temporal fascia': 'Lame superficielle du fascia temporal',
  'Masseteric fascia': 'Fascia massétérique',
  'Superficial investing cervical fascia': 'Lame superficielle du fascia cervical',
  'Posterior layer of thoracolumbar fascia': 'Lame postérieure du fascia thoraco-lombal',
  'Middle layer of thoracolumbar fascia': 'Lame moyenne du fascia thoraco-lombal',
  'Anterior layer of thoracolumbar fascia': 'Lame antérieure du fascia thoraco-lombal',
  'Investing abdominal fascia': 'Fascia abdominal superficiel',
  'Piriformis fascia': 'Fascia du muscle piriforme',
  'Deltoid fascia': 'Fascia deltoïdien',
  'Brachial fascia': 'Fascia brachial',
  'Antebrachial fascia': 'Fascia antébrachial',
  'Extensor retinaculum of wrist': 'Rétinaculum des extenseurs du poignet',
  'Flexor retinaculum of wrist': 'Rétinaculum des fléchisseurs du poignet',
  'Dorsal fascia of hand': 'Fascia dorsal de la main',
  'Superficial transverse metacarpal ligament': 'Ligament métacarpien transverse superficiel',
  'Palmar aponeurosis': 'Aponévrose palmaire',
  'Lateral patellar retinaculum': 'Rétinaculum patellaire latéral',
  'Medial patellar retinaculum': 'Rétinaculum patellaire médial',
  'Medial femoral intermuscular septum': 'Septum intermusculaire fémoral médial',
  'Lateral femoral intermuscular septum': 'Septum intermusculaire fémoral latéral',
  'Popliteal fascia': 'Fascia poplité',
  'Crural fascia': 'Fascia crural',
  'Anterior intermuscular septum of leg': 'Septum intermusculaire antérieur de la jambe',
  'Posterior intermuscular septum of leg': 'Septum intermusculaire postérieur de la jambe',
  'Transverse intermuscular septum of leg': 'Septum intermusculaire transverse de la jambe',
  'Superior extensor retinaculum of ankle': 'Rétinaculum supérieur des extenseurs',
  'Inferior extensor retinaculum of ankle': 'Rétinaculum inférieur des extenseurs',
  'Superior fibular retinaculum': 'Rétinaculum supérieur des fibulaires',
  'Inferior fibular retinaculum': 'Rétinaculum inférieur des fibulaires',
  'Superficial transverse metatarsal ligament': 'Ligament métatarsien transverse superficiel',
  'Plantar aponeurosis': 'Aponévrose plantaire',
  'Flexor retinaculum of ankle': 'Rétinaculum des fléchisseurs de la cheville',
  'Clavipectoral fascia': 'Fascia clavi-pectoral',
  'Iliopsoas fascia': 'Fascia ilio-psoas',
  'Diaphragmatic fascia': 'Fascia diaphragmatique',
  // Bourses séreuses
  'Subtendinous bursa of trapezius muscle': 'Bourse subtendineuse du muscle trapèze',
  'Coracobrachial bursa': 'Bourse coraco-brachiale',
  'Subtendinous bursa of infraspinatus muscle': 'Bourse subtendineuse du muscle infra-épineux',
  'Subtendinous bursa of teres major muscle': 'Bourse subtendineuse du muscle grand rond',
  'Subtendinous bursa of triceps brachii muscle': 'Bourse subtendineuse du muscle triceps brachial',
  'Bicipitoradial bursa': 'Bourse bicipito-radiale',
  'Subcutaneous trochanteric bursa': 'Bourse trochantérique sous-cutanée',
  'Trochanteric bursa of gluteus medius muscle': 'Bourse trochantérique du muscle moyen fessier',
  'Trochanteric bursa of gluteus maximus muscle': 'Bourse trochantérique du muscle grand fessier',
  'Trochanteric bursa of gluteus minimus muscle': 'Bourse trochantérique du muscle petit fessier',
  'Bursa of piriformis muscle': 'Bourse du muscle piriforme',
  'Sciatic bursa of obturator internus': 'Bourse ischiatique du muscle obturateur interne',
  'Subtendinous bursa of obturator internus': 'Bourse subtendineuse du muscle obturateur interne',
  'Sciatic bursa of gluteus maximus muscle': 'Bourse ischiatique du muscle grand fessier',
  'Intermuscular gluteal bursae': 'Bourses intermusculaires fessières',
  'Iliopectineal bursa': 'Bourse ilio-pectinée',
  'Subtendinous bursa of iliacus muscle': 'Bourse subtendineuse du muscle iliaque',
  'Superior bursa of biceps femoris muscle': 'Bourse supérieure du muscle biceps fémoral',
  'Subtendinous prepatellar bursa': 'Bourse prépatellaire subtendineuse',
  'Subcutaneous prepatellar bursa': 'Bourse prépatellaire sous-cutanée',
  'Deep infrapatellar bursa': 'Bourse infrapatellaire profonde',
  'Subfacial prepatellar bursa': 'Bourse prépatellaire subfasciale',
  'Subcutaneous infrapatellar bursa': 'Bourse infrapatellaire sous-cutanée',
  'Suprapatellar bursa': 'Bourse suprapatellaire',
  'Subcutaneous bursa of tuberosity of tibia': 'Bourse sous-cutanée de la tubérosité tibiale',
  'Inferior subtendinous bursa of biceps femoris muscle': 'Bourse subtendineuse inférieure du muscle biceps fémoral',
  'Subtendinous bursa of sartorius muscle': 'Bourse subtendineuse du muscle sartorius',
  'Anserine bursa': 'Bourse ansérine (de la patte d’oie)',
  'Medial subtendinous bursa of gastrocnemius muscle': 'Bourse subtendineuse médiale du muscle gastrocnémien',
  'Lateral subtendinous bursa of gastrocnemius muscle': 'Bourse subtendineuse latérale du muscle gastrocnémien',
  'Semimembranosus bursa': 'Bourse du muscle semi-membraneux',
  'Subcutaneous bursa of lateral malleolus': 'Bourse sous-cutanée de la malléole latérale',
  'Subcutaneous bursa of medial malleolus': 'Bourse sous-cutanée de la malléole médiale',
  'Subtendinous bursa of tibialis anterior': 'Bourse subtendineuse du muscle tibial antérieur',
  'Subcutaneous calcaneal bursa': 'Bourse calcanéenne sous-cutanée',
  'Subtendinous calcaneal bursa': 'Bourse du tendon calcanéen',
  // Gaines tendineuses
  'Intertubercular tendon sheath': 'Gaine tendineuse intertuberculaire',
  'Tendon sheath of flexor pollicis longus': 'Gaine tendineuse du muscle long fléchisseur du pouce',
  'Tendon sheath of flexor carpi radialis': 'Gaine tendineuse du muscle fléchisseur radial du carpe',
  'Common flexor tendon sheath': 'Gaine commune des tendons fléchisseurs',
  'Tendon sheath of extensor carpi ulnaris': 'Gaine tendineuse du muscle extenseur ulnaire du carpe',
  'Synovial sheaths of digits of hand': 'Gaines synoviales des doigts',
  'Cruciform part of fibrous sheath of digit of hand': 'Partie cruciforme de la gaine fibreuse des doigts',
  'Tendon sheath of extensor digiti minimi manus': 'Gaine tendineuse du muscle extenseur du petit doigt',
  'Tendon sheath of extensor pollicis longus': 'Gaine tendineuse du muscle long extenseur du pouce',
  'Tendon sheath - abd. pollicis longus - ext. pollicis brevis': 'Gaine tendineuse du long abducteur et du court extenseur du pouce',
  'Tendon sheath of extensors carpi radialis': 'Gaine tendineuse des muscles extenseurs radiaux du carpe',
  'Tendon sheath of extensor digitorum and extensor indicis': 'Gaine tendineuse des muscles extenseur des doigts et extenseur de l’index',
  'Tendon sheath of tibialis anterior': 'Gaine tendineuse du muscle tibial antérieur',
  'Tendon sheath of extensor hallucis longus': 'Gaine tendineuse du muscle long extenseur de l’hallux',
  'Tendon sheath of extensor digitorum longus': 'Gaine tendineuse du muscle long extenseur des orteils',
  'Tendon sheath of flexor digitorum longus': 'Gaine tendineuse du muscle long fléchisseur des orteils',
  'Tendon sheath of tibialis posterior muscle': 'Gaine tendineuse du muscle tibial postérieur',
  'Tendon sheath of flexor hallucis longus': 'Gaine tendineuse du muscle long fléchisseur de l’hallux',
  'Common tendon sheath of fibularis muscles': 'Gaine tendineuse commune des muscles fibulaires',
  'Plantar tendon sheath of fibularis longus muscle': 'Gaine tendineuse plantaire du muscle long fibulaire',

  // -------------------------------------------------------------------- nerfs
  'Sensory root of trigeminal nerve': 'Racine sensitive du nerf trijumeau',
  'Meningeal branch of maxillary nerve': 'Rameau méningé du nerf maxillaire',
  'Motor root of trigeminal nerve': 'Racine motrice du nerf trijumeau',
  'Roots of brachial plexus': 'Racines du plexus brachial',
  'Superior trunk of brachial plexus': 'Tronc supérieur du plexus brachial',
  'Middle trunk of brachial plexus': 'Tronc moyen du plexus brachial',
  'Inferior trunk of brachial plexus': 'Tronc inférieur du plexus brachial',
  'Anterior division of superior trunk of brachial plexus': 'Division antérieure du tronc supérieur',
  'Posterior division of superior trunk of brachial plexus': 'Division postérieure du tronc supérieur',
  'Anterior division of middle trunk of brachial plexus': 'Division antérieure du tronc moyen',
  'Posterior division of middle trunk of brachial plexus': 'Division postérieure du tronc moyen',
  'Anterior division of inferior trunk of brachial plexus': 'Division antérieure du tronc inférieur',
  'Posterior division of inferior trunk of brachial plexus': 'Division postérieure du tronc inférieur',
  'Posterior cord of brachial plexus': 'Faisceau postérieur du plexus brachial',
  'Dorsal scapular nerve': 'Nerf dorsal de la scapula',
  'Lateral antebrachial cutaneous nerve': 'Nerf cutané latéral de l’avant-bras',
  'Deep branch of radial nerve': 'Branche profonde du nerf radial',
  'Posterior interosseous nerve of forearm': 'Nerf interosseux postérieur',
  'Superficial branch of radial nerve': 'Branche superficielle du nerf radial',
  'Dorsal digital branches of radial nerve': 'Nerfs digitaux dorsaux du nerf radial',
  'Posterior antebrachial cutaneous nerve': 'Nerf cutané postérieur de l’avant-bras',
  'Inferior lateral brachial cutaneous nerve': 'Nerf cutané latéral inférieur du bras',
  'Muscular branches of radial nerve': 'Rameaux musculaires du nerf radial',
  'Superior lateral brachial cutaneous nerve': 'Nerf cutané latéral supérieur du bras',
  'Muscular branches of axillary nerve': 'Rameaux musculaires du nerf axillaire',
  'Medial antebrachial cutaneous nerve': 'Nerf cutané médial de l’avant-bras',
  'Anterior branch of medial antebrachial cutaneous nerve': 'Branche antérieure du nerf cutané médial de l’avant-bras',
  'Posterior branch of medial antebrachial cutaneous nerve': 'Branche postérieure du nerf cutané médial de l’avant-bras',
  'Ulnar nerve': 'Nerf ulnaire',
  'Dorsal branch of ulnar nerve': 'Branche dorsale du nerf ulnaire',
  'Dorsal digital branches of ulnar nerve': 'Nerfs digitaux dorsaux du nerf ulnaire',
  'Palmar branch of ulnar nerve': 'Rameau palmaire du nerf ulnaire',
  'Superficial branch of ulnar nerve': 'Branche superficielle du nerf ulnaire',
  'Deep branch of ulnar nerve': 'Branche profonde du nerf ulnaire',
  'Common palmar digital branches of ulnar nerve': 'Nerfs digitaux palmaires communs du nerf ulnaire',
  'Proper palmar digital branches of ulnar nerve': 'Nerfs digitaux palmaires propres du nerf ulnaire',
  'Muscular branches of ulnar nerve': 'Rameaux musculaires du nerf ulnaire',
  'Median nerve': 'Nerf médian',
  'Anterior interosseous nerve of forearm': 'Nerf interosseux antérieur',
  'Palmar branch of median nerve': 'Rameau palmaire du nerf médian',
  'Muscular branches of median nerve': 'Rameaux musculaires du nerf médian',
  'Common palmar digital branches of median nerve': 'Nerfs digitaux palmaires communs du nerf médian',
  'Proper palmar digital branches of median nerve': 'Nerfs digitaux palmaires propres du nerf médian',
  'Communicating branch of median nerve with ulnar nerve': 'Rameau communicant du nerf médian avec le nerf ulnaire',
  'Intercostal nerves': 'Nerfs intercostaux',
  'Iliohypogastric nerve': 'Nerf ilio-hypogastrique',
  'Ilio-inguinal nerve': 'Nerf ilio-inguinal',
  'Genitofemoral nerve': 'Nerf génito-fémoral',
  'Femoral branch of genitofemoral nerve': 'Rameau fémoral du nerf génito-fémoral',
  'Genital branch of genitofemoral nerve': 'Rameau génital du nerf génito-fémoral',
  'Lateral femoral cutaneous nerve': 'Nerf cutané latéral de la cuisse',
  'Femoral nerve': 'Nerf fémoral',
  'Anterior cutaneous branches of femoral nerve': 'Rameaux cutanés antérieurs du nerf fémoral',
  'Saphenous nerve': 'Nerf saphène',
  'Infrapatellar branch of saphenous nerve': 'Rameau infrapatellaire du nerf saphène',
  'Medial crural cutaneous branches of saphenous nerve': 'Rameaux cutanés médiaux de la jambe (nerf saphène)',
  'Obturator nerve': 'Nerf obturateur',
  'Anterior branch of obturator nerve': 'Branche antérieure du nerf obturateur',
  'Posterior branch of obturator nerve': 'Branche postérieure du nerf obturateur',
  'Superior gluteal nerve': 'Nerf glutéal supérieur',
  'Nerve to piriformis muscle': 'Nerf du muscle piriforme',
  'Nerve to quadratus femoris muscle': 'Nerf du muscle carré fémoral',
  'Posterior femoral cutaneous nerve': 'Nerf cutané postérieur de la cuisse',
  'Anterior root of posterior femoral cutaneous nerve': 'Racine antérieure du nerf cutané postérieur de la cuisse',
  'Posterior root of posterior femoral cutaneous nerve': 'Racine postérieure du nerf cutané postérieur de la cuisse',
  'Pudendal nerve': 'Nerf pudendal',
  'Sciatic nerve': 'Nerf ischiatique (sciatique)',
  'Tibial nerve': 'Nerf tibial',
  'Medial sural cutaneous nerve': 'Nerf cutané sural médial',
  'Sural nerve': 'Nerf sural',
  'Sural communicating branch of common fibular nerve': 'Rameau communicant sural du nerf fibulaire commun',
  'Medial plantar nerve': 'Nerf plantaire médial',
  'Lateral plantar nerve': 'Nerf plantaire latéral',
  'Common plantar digital branches of medial plantar nerve': 'Nerfs digitaux plantaires communs du nerf plantaire médial',
  'Proper plantar digital branches of medial plantar nerve': 'Nerfs digitaux plantaires propres du nerf plantaire médial',
  'Common plantar digital branches of lateral plantar nerve': 'Nerfs digitaux plantaires communs du nerf plantaire latéral',
  'Proper plantar digital branches of lateral plantar nerve': 'Nerfs digitaux plantaires propres du nerf plantaire latéral',
  'Common fibular nerve': 'Nerf fibulaire commun',
  'Superficial fibular nerve': 'Nerf fibulaire superficiel',
  'Dorsal digital branches of superficial fibular nerve': 'Nerfs digitaux dorsaux du nerf fibulaire superficiel',
  'Medial dorsal cutaneous nerve of foot': 'Nerf cutané dorsal médial du pied',
  'Intermediate dorsal cutaneous nerve of foot': 'Nerf cutané dorsal intermédiaire du pied',
  'Deep fibular nerve': 'Nerf fibulaire profond',
  'Muscular branches of deep fibular nerve': 'Rameaux musculaires du nerf fibulaire profond',
  'Dorsal digital branches of deep fibular nerve': 'Nerfs digitaux dorsaux du nerf fibulaire profond',
  'Sympathetic trunk': 'Tronc sympathique',
  'Ganglia of sympathetic trunk': 'Ganglions du tronc sympathique',
  'Sympathetic nerves': 'Nerfs sympathiques',
  'Posterior root of spinal nerve': 'Racine postérieure du nerf spinal',
  'Anterior root of spinal nerve': 'Racine antérieure du nerf spinal',
  'Cauda equina': 'Queue de cheval',

  // --------------------------------------------- encéphale et moelle spinale
  'Spinal dura': 'Dure-mère spinale',
  'White matter of spinal cord': 'Moelle spinale',
  'Posterior horn of spinal cord': 'Corne postérieure de la moelle',
  'Anterior horn of spinal cord': 'Corne antérieure de la moelle',
  'Gracile fasciculus': 'Faisceau gracile',
  'Cuneate fasciculus': 'Faisceau cunéiforme',
  'Central canal': 'Canal central de la moelle',
  'Septal nuclei': 'Noyaux septaux',
  'Stria terminalis': 'Strie terminale',
  'Stria medullaris thalami': 'Strie médullaire du thalamus',
  'Medial geniculate body': 'Corps géniculé médial',
  'Interpeduncular fossa': 'Fosse interpédonculaire',
  'Pyramid of medulla oblongata': 'Pyramide de la moelle allongée',
  'Olive': 'Olive bulbaire',
  'Peduncle of flocculus': 'Pédoncule du flocculus',
  'Nucleus of oculomotor nerve': 'Noyau du nerf oculomoteur (III)',
  'Accessory nucleus of oculomotor nerve': 'Noyau accessoire du nerf oculomoteur (d’Edinger-Westphal)',
  'Nucleus of trochlear nerve': 'Noyau du nerf trochléaire (IV)',
  'Nucleus of abducens nerve': 'Noyau du nerf abducens (VI)',
  'Motor nucleus of facial nerve': 'Noyau moteur du nerf facial (VII)',
  'Anterior cochlear nucleus': 'Noyau cochléaire antérieur',
  'Posterior cochlear nucleus': 'Noyau cochléaire postérieur',
  'Nucleus of solitary tract': 'Noyau du tractus solitaire',
  'Posterior nucleus of vagus nerve': 'Noyau dorsal du nerf vague (X)',
  'Nucleus of accessory nerve': 'Noyau du nerf accessoire (XI)',
  'Nucleus of hypoglossal nerve': 'Noyau du nerf hypoglosse (XII)',

  // ------------------------------------------------------------------- cœur
  'Inferior leaflet of right atrioventricular valve': 'Cuspide inférieure de la valve tricuspide',
  'Septal leaflet of right atrioventricular valve': 'Cuspide septale de la valve tricuspide',
  'Posterior leaflet of left atrioventricular valve': 'Cuspide postérieure de la valve mitrale',
  'Left coronary leaflet': 'Valvule semi-lunaire coronaire gauche (aortique)',
  'Non-coronary leaflet': 'Valvule semi-lunaire non coronaire (aortique)',
  'Right coronary leaflet': 'Valvule semi-lunaire coronaire droite (aortique)',
  'Anterior semilunar leaflet of pulmonary valve': 'Valvule semi-lunaire antérieure (pulmonaire)',
  'Left semilunar leaflet of pulmonary valve': 'Valvule semi-lunaire gauche (pulmonaire)',
  'Right semilunar leaflet of pulmonary valve': 'Valvule semi-lunaire droite (pulmonaire)',
  'Inferior papillary muscle of right ventricle': 'Muscle papillaire inférieur du ventricule droit',
  'Anterior papillary muscle of right ventricle': 'Muscle papillaire antérieur du ventricule droit',
  'Septal papillary muscle of right ventricle': 'Muscle papillaire septal du ventricule droit',
  'Inferior papillary muscle of left ventricle': 'Muscle papillaire inférieur du ventricule gauche',

  // ----------------------------------------------------------------- artères
  'Bifurcation of pulmonary trunk': 'Bifurcation du tronc pulmonaire',
  'Right pulmonary artery': 'Artère pulmonaire droite',
  'Left pulmonary artery': 'Artère pulmonaire gauche',
  'Superior lobar artery of right lung': 'Artère lobaire supérieure du poumon droit',
  'Middle lobar artery of right lung': 'Artère lobaire moyenne du poumon droit',
  'Inferior lobar artery of right lung': 'Artère lobaire inférieure du poumon droit',
  'Apical segmental artery of right lung': 'Artère segmentaire apicale du poumon droit',
  'Anterior segmental artery of right lung': 'Artère segmentaire antérieure du poumon droit',
  'Posterior segmental artery of right lung': 'Artère segmentaire postérieure du poumon droit',
  'Medial segmental artery of right lung': 'Artère segmentaire médiale du poumon droit',
  'Lateral segmental artery of right lung': 'Artère segmentaire latérale du poumon droit',
  'Superior segmental artery of right lung': 'Artère segmentaire supérieure du poumon droit',
  'Posterior basal segmental artery of right lung': 'Artère segmentaire basale postérieure du poumon droit',
  'Lateral basal segmental artery of right lung': 'Artère segmentaire basale latérale du poumon droit',
  'Anterior basal segmental artery of right lung': 'Artère segmentaire basale antérieure du poumon droit',
  'Medial basal segmental artery of right lung': 'Artère segmentaire basale médiale du poumon droit',
  'Superior lingular artery of left lung': 'Artère lingulaire supérieure du poumon gauche',
  'Inferior lingular artery of left lung': 'Artère lingulaire inférieure du poumon gauche',
  'Apical segmental artery of left lung': 'Artère segmentaire apicale du poumon gauche',
  'Posterior segmental artery of left lung': 'Artère segmentaire postérieure du poumon gauche',
  'Anterior segmental artery of left lung': 'Artère segmentaire antérieure du poumon gauche',
  'Superior segmental artery of left lung': 'Artère segmentaire supérieure du poumon gauche',
  'Lateral basal segmental artery of left lung': 'Artère segmentaire basale latérale du poumon gauche',
  'Posterior basal segmental artery of left lung': 'Artère segmentaire basale postérieure du poumon gauche',
  'Medial basal segmental artery of left lung': 'Artère segmentaire basale médiale du poumon gauche',
  'Anterior basal segmental artery of left lung': 'Artère segmentaire basale antérieure du poumon gauche',
  'Right inferolateral branch of right coronary artery': 'Rameau inféro-latéral de l’artère coronaire droite',
  'Septal branches of anterior interventricular artery': 'Rameaux septaux de l’artère interventriculaire antérieure',
  'Thoracic aorta': 'Aorte thoracique',
  'Abdominal aorta': 'Aorte abdominale',
  'Posterior intercostal arteries': 'Artères intercostales postérieures',
  'First posterior intercostal artery': 'Première artère intercostale postérieure',
  'Second posterior intercostal artery': 'Deuxième artère intercostale postérieure',
  'Subcostal artery': 'Artère subcostale',
  'Superior phrenic arteries': 'Artères phréniques supérieures',
  'Lumbar arteries': 'Artères lombales',
  'Coeliac trunk': 'Tronc cœliaque',
  'Inferior pancreaticoduodenal artery': 'Artère pancréatico-duodénale inférieure',
  'Anterior inferior pancreaticoduodenal artery': 'Artère pancréatico-duodénale inférieure antérieure',
  'Middle colic artery': 'Artère colique moyenne',
  'Right colic artery': 'Artère colique droite',
  'Ileocolic artery': 'Artère iléo-colique',
  'Colic branch of ileocolic artery': 'Rameau colique de l’artère iléo-colique',
  'Ileal branch of ileocolic artery': 'Rameau iléal de l’artère iléo-colique',
  'Appendicular artery': 'Artère appendiculaire',
  'Marginal artery': 'Artère marginale du côlon',
  'Ascending branch of left colic artery': 'Branche ascendante de l’artère colique gauche',
  'Descending branch of left colic artery': 'Branche descendante de l’artère colique gauche',
  'Sigmoid arteries': 'Artères sigmoïdiennes',
  'Superior anorectal artery': 'Artère rectale supérieure',
  'Right renal artery': 'Artère rénale droite',
  'Left renal artery': 'Artère rénale gauche',
  'Anterior branch of renal artery': 'Branche antérieure de l’artère rénale',
  'Posterior branch of renal artery': 'Branche postérieure de l’artère rénale',
  'Intrarenal arteries of left kidney': 'Artères intrarénales du rein gauche',
  'Intrarenal arteries of right kidney': 'Artères intrarénales du rein droit',
  'Right testicular artery': 'Artère testiculaire droite',
  'Left testicular artery': 'Artère testiculaire gauche',
  'Anterior division of internal iliac artery': 'Tronc antérieur de l’artère iliaque interne',
  'Posterior division of internal iliac artery': 'Tronc postérieur de l’artère iliaque interne',
  'Iliacus branch of iliolumbar artery': 'Rameau iliaque de l’artère ilio-lombale',
  'Lumbar branch of iliolumbar artery': 'Rameau lombal de l’artère ilio-lombale',
  'Spinal branch of iliolumbar artery': 'Rameau spinal de l’artère ilio-lombale',
  'Deep artery of penis': 'Artère profonde du pénis',
  'Frontal branch of superficial temporal artery': 'Branche frontale de l’artère temporale superficielle',
  'Transverse facial artery': 'Artère transverse de la face',
  'Buccal artery': 'Artère buccale',
  'Infra-orbital artery': 'Artère infra-orbitaire',
  'Mental branch of inferior alveolar artery': 'Rameau mentonnier de l’artère alvéolaire inférieure',
  'Mylohyoid branch of inferior alveolar artery': 'Rameau mylo-hyoïdien de l’artère alvéolaire inférieure',
  'Accessory branch of middle meningeal artery': 'Rameau accessoire de l’artère méningée moyenne',
  'Anterior deep temporal artery': 'Artère temporale profonde antérieure',
  'Posterior deep temporal artery': 'Artère temporale profonde postérieure',
  'Posterior superior alveolar artery': 'Artère alvéolaire supéro-postérieure',
  'Posterior lateral nasal branches of sphenopalatine artery.': 'Rameaux nasaux postéro-latéraux de l’artère sphéno-palatine',
  'Posterior septal branches of sphenopalatine artery': 'Rameaux septaux postérieurs de l’artère sphéno-palatine',
  'Anterior septal branches of anterior ethmoidal artery': 'Rameaux septaux antérieurs de l’artère ethmoïdale antérieure',
  'Septal branches of posterior ethmoidal artery': 'Rameaux septaux de l’artère ethmoïdale postérieure',
  'Supratrochlear artery': 'Artère supratrochléaire',
  'Callosomarginal artery': 'Artère calloso-marginale',
  'Frontal branches of callosomarginal artery': 'Rameaux frontaux de l’artère calloso-marginale',
  'Pericallosal artery': 'Artère péricalleuse',
  'Orbitofrontal branches of anterior cerebral artery': 'Rameaux orbito-frontaux de l’artère cérébrale antérieure',
  'Proximal lateral striate branches': 'Artères striées latérales proximales',
  'Distal lateral striate branches': 'Artères striées latérales distales',
  'Insular branches of middle cerebral artery (M2)': 'Rameaux insulaires de l’artère cérébrale moyenne (M2)',
  'Insular branches of middle cerebral artery (M2-segment)': 'Rameaux insulaires de l’artère cérébrale moyenne (M2)',
  'Middle cerebral artery (M3-segment)': 'Artère cérébrale moyenne (segment M3)',
  'Middle cerebral artery (M3 segment)': 'Artère cérébrale moyenne (segment M3)',
  'Anterior temporal branch': 'Rameau temporal antérieur',
  'Temporal branches of middle cerebral artery': 'Rameaux temporaux de l’artère cérébrale moyenne',
  'Posterior temporal branch': 'Rameau temporal postérieur',
  'Branch to angular gyrus': 'Rameau du gyrus angulaire',
  'Temporo-occipital branch': 'Rameau temporo-occipital',
  'Prefrontal artery': 'Artère préfrontale',
  'Lateral frontobasal artery': 'Artère fronto-basale latérale',
  'Posterior parietal artery': 'Artère pariétale postérieure',
  'Artery of central sulcus': 'Artère du sillon central',
  'Artery of precentral sulcus': 'Artère du sillon précentral',
  'Postcentral arterial branch': 'Rameau artériel postcentral',
  'Parietal branches of middle cerebral artery': 'Rameaux pariétaux de l’artère cérébrale moyenne',
  'Anterior inferior cerebellar artery': 'Artère cérébelleuse antéro-inférieure',
  'Lateral pontine branches of basilar artery': 'Rameaux pontiques latéraux de l’artère basilaire',
  'Medial pontine branches of basilar artery': 'Rameaux pontiques médiaux de l’artère basilaire',
  'Lateral occipital artery': 'Artère occipitale latérale',
  'Medial occipital artery': 'Artère occipitale médiale',
  'Parieto-occipital artery': 'Artère pariéto-occipitale',
  'Thyrocervical trunk': 'Tronc thyro-cervical',
  'Costocervical trunk': 'Tronc costo-cervical',
  'Deep cervical artery': 'Artère cervicale profonde',
  'Suprascapular artery': 'Artère suprascapulaire',
  'Deep branch of transverse cervical artery': 'Branche profonde de l’artère transverse du cou',
  'Superficial branch of transverse cervical artery': 'Branche superficielle de l’artère transverse du cou',
  'Superior epigastric artery': 'Artère épigastrique supérieure',
  'Pectoral branches of thoraco-acromial artery': 'Rameaux pectoraux de l’artère thoraco-acromiale',
  'Thoracodorsal artery': 'Artère thoraco-dorsale',
  'Anterior circumflex humeral artery': 'Artère circonflexe humérale antérieure',
  'Posterior circumflex humeral artery': 'Artère circonflexe humérale postérieure',
  'Deep brachial artery': 'Artère profonde du bras',
  'Radial collateral artery': 'Artère collatérale radiale',
  'Middle collateral artery': 'Artère collatérale moyenne',
  'Ulnar recurrent artery': 'Artère récurrente ulnaire',
  'Common interosseous artery': 'Artère interosseuse commune',
  'Recurrent interosseous artery': 'Artère interosseuse récurrente',
  'Posterior interosseous artery': 'Artère interosseuse postérieure',
  'Palmar carpal branch of radial artery': 'Rameau carpien palmaire de l’artère radiale',
  'Dorsal carpal branch of ulnar artery': 'Rameau carpien dorsal de l’artère ulnaire',
  'Dorsal carpal anastomosis': 'Réseau carpien dorsal',
  'Superficial palmar arch': 'Arcade palmaire superficielle',
  'Palmar metacarpal arteries': 'Artères métacarpiennes palmaires',
  'Dorsal metacarpal arteries': 'Artères métacarpiennes dorsales',
  'Common palmar digital arteries': 'Artères digitales palmaires communes',
  'Proper palmar digital arteries': 'Artères digitales palmaires propres',
  'Dorsal digital arteries of hand': 'Artères digitales dorsales de la main',
  'Medial circumflex femoral artery': 'Artère circonflexe fémorale médiale',
  'Lateral circumflex femoral artery': 'Artère circonflexe fémorale latérale',
  'Descending branch of lateral circumflex femoral artery': 'Branche descendante de l’artère circonflexe fémorale latérale',
  'Perforating femoral arteries': 'Artères perforantes de la cuisse',
  'Superior medial genicular artery': 'Artère supéro-médiale du genou',
  'Superior lateral genicular artery': 'Artère supéro-latérale du genou',
  'Middle genicular artery': 'Artère moyenne du genou',
  'Inferior medial genicular artery': 'Artère inféro-médiale du genou',
  'Inferior lateral genicular artery': 'Artère inféro-latérale du genou',
  'Patellar anastomosis': 'Réseau articulaire patellaire',
  'Calcaneal branches of fibular artery': 'Rameaux calcanéens de l’artère fibulaire',
  'Calcaneal branches of posterior tibial artery': 'Rameaux calcanéens de l’artère tibiale postérieure',
  'Superficial branch of medial plantar artery': 'Branche superficielle de l’artère plantaire médiale',
  'Plantar arch': 'Arcade plantaire profonde',
  'Plantar metatarsal arteries': 'Artères métatarsiennes plantaires',
  'Perforating branches of plantar metatarsal arteries': 'Rameaux perforants des artères métatarsiennes plantaires',
  'Common plantar digital arteries': 'Artères digitales plantaires communes',
  'Proper plantar digital arteries': 'Artères digitales plantaires propres',
  'Arcuate artery': 'Artère arquée du pied',
  'Lateral tarsal artery': 'Artère tarsienne latérale',
  'Dorsal metatarsal arteries': 'Artères métatarsiennes dorsales',
  'Dorsal digital arteries of foot': 'Artères digitales dorsales du pied',

  // ------------------------------------------------------------------ veines
  'Right superior pulmonary vein': 'Veine pulmonaire supérieure droite',
  'Right inferior pulmonary vein': 'Veine pulmonaire inférieure droite',
  'Left superior pulmonary vein': 'Veine pulmonaire supérieure gauche',
  'Left inferior pulmonary vein': 'Veine pulmonaire inférieure gauche',
  'Apical vein of right lung': 'Veine apicale du poumon droit',
  'Anterior vein of right lung': 'Veine antérieure du poumon droit',
  'Posterior vein of right lung': 'Veine postérieure du poumon droit',
  'Medial vein of right lung': 'Veine médiale du poumon droit',
  'Lateral vein of right lung': 'Veine latérale du poumon droit',
  'Superior vein of right lung': 'Veine supérieure du poumon droit',
  'Superior basal vein of right lung': 'Veine basale supérieure du poumon droit',
  'Inferior basal vein of right lung': 'Veine basale inférieure du poumon droit',
  'Apicoposterior vein of left lung': 'Veine apico-postérieure du poumon gauche',
  'Anterior vein of left lung': 'Veine antérieure du poumon gauche',
  'Lingular vein of left lung': 'Veine lingulaire du poumon gauche',
  'Superior lingular vein of left lung': 'Veine lingulaire supérieure du poumon gauche',
  'Inferior lingular vein of left lung': 'Veine lingulaire inférieure du poumon gauche',
  'Superior vein of left lung': 'Veine supérieure du poumon gauche',
  'Superior basal vein of left lung': 'Veine basale supérieure du poumon gauche',
  'Inferior basal vein of left lung': 'Veine basale inférieure du poumon gauche',
  'Middle cardiac vein': 'Veine cardiaque moyenne',
  'Inferior vein of left ventricle': 'Veine inférieure du ventricule gauche',
  'Azygos vein': 'Veine azygos',
  'Hemi-azygos vein': 'Veine hémi-azygos',
  'Accessory hemi-azygos vein': 'Veine hémi-azygos accessoire',
  'Right ascending lumbar vein': 'Veine lombale ascendante droite',
  'Left ascending lumbar vein': 'Veine lombale ascendante gauche',
  'Right subcostal vein': 'Veine subcostale droite',
  'Left subcostal vein': 'Veine subcostale gauche',
  'Right superior phrenic vein': 'Veine phrénique supérieure droite',
  'Right superior intercostal vein': 'Veine intercostale supérieure droite',
  'Left superior intercostal vein': 'Veine intercostale supérieure gauche',
  'Vertebral vein': 'Veine vertébrale',
  'Internal thoracic veins': 'Veines thoraciques internes',
  'Musculophrenic veins': 'Veines musculo-phréniques',
  'Superior epigastric veins': 'Veines épigastriques supérieures',
  'Angular vein': 'Veine angulaire',
  'Submental vein': 'Veine submentale',
  'Superior labial vein': 'Veine labiale supérieure',
  'Inferior labial veins': 'Veines labiales inférieures',
  'Superior ophthalmic vein': 'Veine ophtalmique supérieure',
  'Inferior ophthalmic vein': 'Veine ophtalmique inférieure',
  'Superior thyroid vein': 'Veine thyroïdienne supérieure',
  'Occipital vein': 'Veine occipitale',
  'Superficial temporal veins': 'Veines temporales superficielles',
  'Posterior auricular vein': 'Veine auriculaire postérieure',
  'Maxillary veins': 'Veines maxillaires',
  'Lingual vein': 'Veine linguale',
  'Common facial vein': 'Tronc thyro-linguo-facial (veine faciale commune)',
  'Anterior division of retromandibular vein': 'Branche antérieure de la veine rétromandibulaire',
  'Posterior division of retromandibular vein': 'Branche postérieure de la veine rétromandibulaire',
  'Anterior intercavernous sinus': 'Sinus intercaverneux antérieur',
  'Posterior intercavernous sinus': 'Sinus intercaverneux postérieur',
  'Suprascapular vein': 'Veine suprascapulaire',
  'Right subclavian vein': 'Veine subclavière droite',
  'Left subclavian vein': 'Veine subclavière gauche',
  'Axillary vein': 'Veine axillaire',
  'Subscapular vein': 'Veine subscapulaire',
  'Circumflex scapular vein': 'Veine circonflexe de la scapula',
  'Thoracodorsal vein': 'Veine thoraco-dorsale',
  'Lateral thoracic vein': 'Veine thoracique latérale',
  'Anterior circumflex humeral vein': 'Veine circonflexe humérale antérieure',
  'Posterior circumflex humeral vein': 'Veine circonflexe humérale postérieure',
  'Cephalic vein': 'Veine céphalique',
  'Basilic vein': 'Veine basilique',
  'Median cubital vein': 'Veine médiane du coude',
  'Median antebrachial vein': 'Veine médiane de l’avant-bras',
  'Brachial veins': 'Veines brachiales',
  'Radial veins': 'Veines radiales',
  'Ulnar veins': 'Veines ulnaires',
  'Superficial venous palmar arch': 'Arcade veineuse palmaire superficielle',
  'Deep venous palmar arch': 'Arcade veineuse palmaire profonde',
  'Palmar digital veins': 'Veines digitales palmaires',
  'Dorsal digital veins of hand': 'Veines digitales dorsales de la main',
  'Hepatic veins': 'Veines hépatiques',
  'Hepatic portal vein': 'Veine porte hépatique',
  'Splenic vein': 'Veine splénique',
  'Superior mesenteric vein': 'Veine mésentérique supérieure',
  'Inferior mesenteric vein': 'Veine mésentérique inférieure',
  'Middle colic vein': 'Veine colique moyenne',
  'Right colic vein': 'Veine colique droite',
  'Sigmoid veins': 'Veines sigmoïdiennes',
  'Right gastro-omental vein': 'Veine gastro-omentale droite',
  'Left gastro-omental vein': 'Veine gastro-omentale gauche',
  'Right renal vein': 'Veine rénale droite',
  'Left renal vein': 'Veine rénale gauche',
  'Intrarenal veins of right kidney': 'Veines intrarénales du rein droit',
  'Intrarenal veins of left kidney': 'Veines intrarénales du rein gauche',
  'Right testicular vein': 'Veine testiculaire droite',
  'Left testicular vein': 'Veine testiculaire gauche',
  'Inferior vena cava (abdominal part)': 'Veine cave inférieure (partie abdominale)',
  'Lumbar veins': 'Veines lombales',
  'Common iliac vein': 'Veine iliaque commune',
  'Internal iliac vein': 'Veine iliaque interne',
  'External iliac vein': 'Veine iliaque externe',
  'Iliolumbar vein': 'Veine ilio-lombale',
  'Lateral sacral veins': 'Veines sacrales latérales',
  'Superior gluteal veins': 'Veines glutéales supérieures',
  'Inferior gluteal veins': 'Veines glutéales inférieures',
  'Internal pudendal vein': 'Veine pudendale interne',
  'External pudendal veins': 'Veines pudendales externes',
  'Inferior epigastric vein': 'Veine épigastrique inférieure',
  'Superficial epigastric vein': 'Veine épigastrique superficielle',
  'Deep dorsal vein of penis': 'Veine dorsale profonde du pénis',
  'Superficial dorsal veins of penis': 'Veines dorsales superficielles du pénis',
  'Femoral vein': 'Veine fémorale',
  'Deep femoral vein': 'Veine fémorale profonde',
  'Lateral circumflex femoral veins': 'Veines circonflexes fémorales latérales',
  'Medial circumflex femoral veins': 'Veines circonflexes fémorales médiales',
  'Perforating veins': 'Veines perforantes',
  'Great saphenous vein': 'Grande veine saphène',
  'Small saphenous vein': 'Petite veine saphène',
  'Popliteal vein': 'Veine poplitée',
  'Genicular veins': 'Veines du genou',
  'Anterior tibial veins': 'Veines tibiales antérieures',
  'Posterior tibial veins': 'Veines tibiales postérieures',
  'Fibular veins': 'Veines fibulaires',
  'Medial plantar veins': 'Veines plantaires médiales',
  'Lateral plantar veins': 'Veines plantaires latérales',
  'Plantar metatarsal veins': 'Veines métatarsiennes plantaires',
  'Plantar digital veins': 'Veines digitales plantaires',
  'Intercapitular veins of foot': 'Veines intercapitulaires du pied',
  'Dorsal metatarsal veins': 'Veines métatarsiennes dorsales',
  'Dorsal digital veins of foot': 'Veines digitales dorsales du pied',

  // -------------------------------------------------------------- lymphatique
  'Left lobe of thymus': 'Lobe gauche du thymus',
  'Right lobe of thymus': 'Lobe droit du thymus',
  'Lymph node': 'Nœud lymphatique',
  'Occipital nodes': 'Nœuds lymphatiques occipitaux',
  'Mastoid nodes': 'Nœuds lymphatiques mastoïdiens',
  'Pre-auricular nodes': 'Nœuds lymphatiques préauriculaires',
  'Infra-auricular nodes': 'Nœuds lymphatiques infra-auriculaires',
  'Superficial parotid nodes': 'Nœuds lymphatiques parotidiens superficiels',
  'Intraglandular parotid nodes': 'Nœuds lymphatiques parotidiens intraglandulaires',
  'Nasolabial node': 'Nœud lymphatique naso-labial',
  'Bucinator node': 'Nœud lymphatique buccinateur',
  'Mandibular node': 'Nœud lymphatique mandibulaire',
  'Submental nodes': 'Nœuds lymphatiques submentaux',
  'Submandibular nodes': 'Nœuds lymphatiques submandibulaires',
  'Superficial anterior cervical nodes': 'Nœuds lymphatiques cervicaux antérieurs superficiels',
  'Superficial lateral cervical nodes': 'Nœuds lymphatiques cervicaux latéraux superficiels',
  'Jugulodigastric node': 'Nœud lymphatique jugulo-digastrique',
  'Lateral superior jugular node': 'Nœud lymphatique jugulaire supérieur latéral',
  'Anterior inferior jugular nodes': 'Nœuds lymphatiques jugulaires inférieurs antérieurs',
  'Inferior deep lateral cervical nodes': 'Nœuds lymphatiques cervicaux latéraux profonds inférieurs',
  'Supraclavicular nodes': 'Nœuds lymphatiques supraclaviculaires',
  'Retropharyngeal nodes': 'Nœuds lymphatiques rétropharyngiens',
  'Pretracheal nodes': 'Nœuds lymphatiques prétrachéaux',
  'Paratracheal cervical nodes': 'Nœuds lymphatiques paratrachéaux cervicaux',
  'Thyroid nodes': 'Nœuds lymphatiques thyroïdiens',
  'Apical axillary nodes': 'Nœuds lymphatiques axillaires apicaux',
  'Central axillary nodes': 'Nœuds lymphatiques axillaires centraux',
  'Lateral axillary nodes': 'Nœuds lymphatiques axillaires latéraux',
  'Anterior axillary nodes': 'Nœuds lymphatiques axillaires antérieurs (pectoraux)',
  'Posterior axillary nodes': 'Nœuds lymphatiques axillaires postérieurs (subscapulaires)',
  'Brachial nodes': 'Nœuds lymphatiques brachiaux',
  'Interpectoral nodes': 'Nœuds lymphatiques interpectoraux',
  'Infraclavicular nodes': 'Nœuds lymphatiques infraclaviculaires',
  'Cubital nodes': 'Nœuds lymphatiques cubitaux',
  'Supratrochlear nodes': 'Nœuds lymphatiques supratrochléaires',
  'Parasternal nodes': 'Nœuds lymphatiques parasternaux',
  'Intercostal nodes': 'Nœuds lymphatiques intercostaux',
  'Superior diaphragmatic nodes': 'Nœuds lymphatiques diaphragmatiques supérieurs',
  'Inferior diaphragmatic nodes': 'Nœuds lymphatiques diaphragmatiques inférieurs',
  'Prepericardial nodes': 'Nœuds lymphatiques prépéricardiques',
  'Lateral pericardial nodes': 'Nœuds lymphatiques péricardiques latéraux',
  'Prevertebral nodes': 'Nœuds lymphatiques prévertébraux',
  'Brachiocephalic nodes': 'Nœuds lymphatiques brachio-céphaliques',
  'Paratracheal thoracic nodes': 'Nœuds lymphatiques paratrachéaux thoraciques',
  'Superior tracheobronchial nodes': 'Nœuds lymphatiques trachéo-bronchiques supérieurs',
  'Inferior tracheobronchial nodes': 'Nœuds lymphatiques trachéo-bronchiques inférieurs',
  'Intrapulmonary nodes': 'Nœuds lymphatiques intrapulmonaires',
  'Juxta-oesophageal nodes': 'Nœuds lymphatiques juxta-œsophagiens',
  'Node of ligamentum arteriosum': 'Nœud lymphatique du ligament artériel',
  'Node of arch of azygos vein': 'Nœud lymphatique de l’arc de la veine azygos',
  'Coeliac nodes': 'Nœuds lymphatiques cœliaques',
  'Right gastric nodes': 'Nœuds lymphatiques gastriques droits',
  'Right gastro-omental nodes': 'Nœuds lymphatiques gastro-omentaux droits',
  'Suprapyloric node': 'Nœud lymphatique suprapylorique',
  'Subpyloric nodes': 'Nœuds lymphatiques subpyloriques',
  'Retropyloric nodes': 'Nœuds lymphatiques rétropyloriques',
  'Superior pancreatic nodes': 'Nœuds lymphatiques pancréatiques supérieurs',
  'Inferior pancreatic nodes': 'Nœuds lymphatiques pancréatiques inférieurs',
  'Splenic nodes': 'Nœuds lymphatiques spléniques',
  'Superior pancreaticoduodenal nodes': 'Nœuds lymphatiques pancréatico-duodénaux supérieurs',
  'Cystic node': 'Nœud lymphatique cystique',
  'Juxta-intestinal mesenteric nodes': 'Nœuds lymphatiques mésentériques juxta-intestinaux',
  'Central superior mesenteric nodes': 'Nœuds lymphatiques mésentériques supérieurs centraux',
  'Paracolic superior mesenteric nodes': 'Nœuds lymphatiques paracoliques',
  'Ileocolic nodes': 'Nœuds lymphatiques iléo-coliques',
  'Precaecal nodes': 'Nœuds lymphatiques précæcaux',
  'Retrocaecal nodes': 'Nœuds lymphatiques rétrocæcaux',
  'Appendicular nodes': 'Nœuds lymphatiques appendiculaires',
  'Right colic nodes': 'Nœuds lymphatiques coliques droits',
  'Middle colic nodes': 'Nœuds lymphatiques coliques moyens',
  'Left colic nodes': 'Nœuds lymphatiques coliques gauches',
  'Sigmoid nodes': 'Nœuds lymphatiques sigmoïdiens',
  'Pre-aortic nodes': 'Nœuds lymphatiques pré-aortiques',
  'Lateral aortic nodes': 'Nœuds lymphatiques latéro-aortiques',
  'Retro-aortic nodes': 'Nœuds lymphatiques rétro-aortiques',
  'Precaval nodes': 'Nœuds lymphatiques précaves',
  'Lateral caval nodes': 'Nœuds lymphatiques latéro-caves',
  'Retrocaval nodes': 'Nœuds lymphatiques rétrocaves',
  'Intermediate lumbar nodes': 'Nœuds lymphatiques lombaux intermédiaires',
  'Subaortic nodes': 'Nœuds lymphatiques subaortiques',
  'Medial common iliac nodes': 'Nœuds lymphatiques iliaques communs médiaux',
  'Intermediate common iliac nodes': 'Nœuds lymphatiques iliaques communs intermédiaires',
  'Lateral common iliac nodes': 'Nœuds lymphatiques iliaques communs latéraux',
  'Medial external iliac nodes': 'Nœuds lymphatiques iliaques externes médiaux',
  'Intermediate external iliac nodes': 'Nœuds lymphatiques iliaques externes intermédiaires',
  'Medial lacunar node': 'Nœud lymphatique lacunaire médial',
  'Intermediate lacunar node': 'Nœud lymphatique lacunaire intermédiaire',
  'Lateral lacunar node': 'Nœud lymphatique lacunaire latéral',
  'Inferior epigastric nodes': 'Nœuds lymphatiques épigastriques inférieurs',
  'Obturator nodes': 'Nœuds lymphatiques obturateurs',
  'Superior gluteal nodes': 'Nœuds lymphatiques glutéaux supérieurs',
  'Inferior gluteal nodes': 'Nœuds lymphatiques glutéaux inférieurs',
  'Median sacral nodes': 'Nœuds lymphatiques sacraux médians',
  'Lateral sacral nodes': 'Nœuds lymphatiques sacraux latéraux',
  'Prevesical nodes': 'Nœuds lymphatiques prévésicaux',
  'Postvesical nodes': 'Nœuds lymphatiques rétrovésicaux',
  'Lateral vesical nodes': 'Nœuds lymphatiques vésicaux latéraux',
  'Pararectal nodes': 'Nœuds lymphatiques pararectaux',
  'Superomedial superficial inguinal nodes': 'Nœuds lymphatiques inguinaux superficiels supéro-médiaux',
  'Superolateral superficial inguinal nodes': 'Nœuds lymphatiques inguinaux superficiels supéro-latéraux',
  'Inferior superficial inguinal nodes': 'Nœuds lymphatiques inguinaux superficiels inférieurs',
  'Proximal deep inguinal node': 'Nœud lymphatique inguinal profond proximal (de Cloquet)',
  'Intermediate deep inguinal node': 'Nœud lymphatique inguinal profond intermédiaire',
  'Superficial popliteal nodes': 'Nœuds lymphatiques poplités superficiels',
  'Deep popliteal nodes': 'Nœuds lymphatiques poplités profonds',
  'Anterior tibial node': 'Nœud lymphatique tibial antérieur',
  'Posterior tibial node': 'Nœud lymphatique tibial postérieur',
  'Fibular node': 'Nœud lymphatique fibulaire',

  // ------------------------------------------------- articulations, ligaments
  'Articular capsule of temporomandibular joint': 'Capsule de l’articulation temporo-mandibulaire',
  'Articular disc of temporomandibular joint': 'Disque de l’articulation temporo-mandibulaire',
  'Lateral temporomandibular ligament': 'Ligament latéral de l’articulation temporo-mandibulaire',
  'Stylomandibular ligament': 'Ligament stylo-mandibulaire',
  'Sphenomandibular ligament': 'Ligament sphéno-mandibulaire',
  'Stylohyoid ligament': 'Ligament stylo-hyoïdien',
  'Lateral thyrohyoid ligament': 'Ligament thyro-hyoïdien latéral',
  'Median thyrohyoid ligament': 'Ligament thyro-hyoïdien médian',
  'Quadrangular membrane': 'Membrane quadrangulaire',
  'Median cricothyroid ligament': 'Ligament crico-thyroïdien médian',
  'Cricopharyngeal ligament': 'Ligament crico-pharyngien',
  'Supraspinous ligament': 'Ligament supra-épineux',
  'Interspinous ligaments': 'Ligaments interépineux',
  'Intercornual ligament': 'Ligament intercornual',
  'Sacrococcygeal symphysis': 'Symphyse sacro-coccygienne',
  'Internal intercostal membrane': 'Membrane intercostale interne',
  'Articular capsule of acromioclavicular joint': 'Capsule de l’articulation acromio-claviculaire',
  'Acromioclavicular ligament': 'Ligament acromio-claviculaire',
  'Articular disc of acromioclavicular joint': 'Disque de l’articulation acromio-claviculaire',
  'Articular capsule of sternoclavicular joint': 'Capsule de l’articulation sterno-claviculaire',
  'Articular disc of sternoclavicular joint': 'Disque de l’articulation sterno-claviculaire',
  'Anterior sternoclavicular ligament': 'Ligament sterno-claviculaire antérieur',
  'Posterior sternoclavicular ligament': 'Ligament sterno-claviculaire postérieur',
  'Articular capsule of glenohumeral joint': 'Capsule de l’articulation gléno-humérale',
  'Superior glenohumeral ligament': 'Ligament gléno-huméral supérieur',
  'Middle glenohumeral ligament': 'Ligament gléno-huméral moyen',
  'Inferior glenohumeral ligament': 'Ligament gléno-huméral inférieur',
  'Glenoid labrum': 'Labrum glénoïdal',
  'Coracohumeral ligament': 'Ligament coraco-huméral',
  'Transverse humeral ligament': 'Ligament huméral transverse',
  'Articular capsule of elbow joint': 'Capsule de l’articulation du coude',
  'Interosseous membrane of forearm': 'Membrane interosseuse de l’avant-bras',
  'Articular disc of distal radio-ulnar joint': 'Disque articulaire radio-ulnaire distal',
  'Palmar radio-ulnar ligament': 'Ligament radio-ulnaire palmaire',
  'Articular capsule of radiocarpal joint': 'Capsule de l’articulation radio-carpienne',
  'Radioscaphocapitate ligament': 'Ligament radio-scapho-capital',
  'Dorsal radiocarpal ligament': 'Ligament radio-carpien dorsal',
  'Ulnocapitate ligament': 'Ligament ulno-capital',
  'Ulnotriquetral ligament': 'Ligament ulno-triquétral',
  'Ulnolunate ligament': 'Ligament ulno-lunaire',
  'Dorsal ulnocarpal ligament': 'Ligament ulno-carpien dorsal',
  'Ulnar collateral ligament of wrist joint': 'Ligament collatéral ulnaire du carpe',
  'Radial collateral ligament of wrist joint': 'Ligament collatéral radial du carpe',
  'Radiate carpal ligament': 'Ligament radié du carpe',
  'Dorsal scaphotriquetral ligament': 'Ligament scapho-triquétral dorsal',
  'Palmar scaphotriquetral ligament': 'Ligament scapho-triquétral palmaire',
  'Dorsal intercarpal ligaments': 'Ligaments intercarpiens dorsaux',
  'Scaphotrapeziotrapezoidal ligament': 'Ligament scapho-trapézo-trapézoïdien',
  'Triquetrocapitate ligament': 'Ligament triquétro-capital',
  'Pisotriquetral ligament': 'Ligament piso-triquétral',
  'Dorsal carpometacarpal ligaments': 'Ligaments carpo-métacarpiens dorsaux',
  'Palmar carpometacarpal ligaments': 'Ligaments carpo-métacarpiens palmaires',
  'Dorsal metacarpal ligaments': 'Ligaments métacarpiens dorsaux',
  'Palmar metacarpal ligaments': 'Ligaments métacarpiens palmaires',
  'Interosseous metacarpal ligaments': 'Ligaments métacarpiens interosseux',
  'Deep transverse metacarpal ligament': 'Ligament métacarpien transverse profond',
  'Articular capsules of metacarpophalangeal joints': 'Capsules des articulations métacarpo-phalangiennes',
  'Collateral metacarpophalangeal ligaments': 'Ligaments collatéraux métacarpo-phalangiens',
  'Articular capsules of proximal interphalangeal joints': 'Capsules des articulations interphalangiennes proximales',
  'Articular capsules of distal interphalangeal joints': 'Capsules des articulations interphalangiennes distales',
  'Collateral interphalangeal ligaments of hand': 'Ligaments collatéraux interphalangiens de la main',
  'Palmar interphalangeal ligaments': 'Ligaments palmaires interphalangiens',
  'Iliolumbar ligament': 'Ligament ilio-lombal',
  'Anterior sacro-iliac ligament': 'Ligament sacro-iliaque antérieur',
  'Posterior sacro-iliac ligament': 'Ligament sacro-iliaque postérieur',
  'Interosseous sacro-iliac ligament': 'Ligament sacro-iliaque interosseux',
  'Interpubic disc': 'Disque interpubien',
  'Superior pubic ligament': 'Ligament pubien supérieur',
  'Inferior pubic ligament': 'Ligament pubien inférieur',
  'Triradiate cartilage': 'Cartilage triradié',
  'Articular capsule of hip joint': 'Capsule de l’articulation coxo-fémorale',
  'Transverse part of iliofemoral ligament': 'Faisceau supérieur du ligament ilio-fémoral',
  'Descending part of iliofemoral ligament': 'Faisceau inférieur du ligament ilio-fémoral',
  'Pubofemoral ligament': 'Ligament pubo-fémoral',
  'Ischiofemoral ligament': 'Ligament ischio-fémoral',
  'Zona orbicularis': 'Zone orbiculaire',
  'Ligament of head of femur': 'Ligament de la tête fémorale (ligament rond)',
  'Transverse acetabular ligament': 'Ligament transverse de l’acétabulum',
  'Acetabular labrum': 'Labrum acétabulaire',
  'Frenula capsulae': 'Freins capsulaires',
  'Articular capsule of knee joint': 'Capsule de l’articulation du genou',
  'Medial meniscus': 'Ménisque médial',
  'Lateral meniscus': 'Ménisque latéral',
  'Anterior meniscotibial ligament (Medial meniscus)': 'Ligament ménisco-tibial antérieur (ménisque médial)',
  'Posterior meniscotibial ligament (Medial meniscus)': 'Ligament ménisco-tibial postérieur (ménisque médial)',
  'Anterior meniscotibial ligament (Lateral meniscus)': 'Ligament ménisco-tibial antérieur (ménisque latéral)',
  'Posterior meniscotibial ligament (Lateral meniscus)': 'Ligament ménisco-tibial postérieur (ménisque latéral)',
  'Superficial part of tibial collateral ligament': 'Partie superficielle du ligament collatéral tibial',
  'Deep part of tibial collateral ligament': 'Partie profonde du ligament collatéral tibial',
  'Meniscopatellar ligament': 'Ligament ménisco-patellaire',
  'Transverse ligament of knee': 'Ligament transverse du genou',
  'Popliteofibular ligament': 'Ligament poplité-fibulaire',
  'Articular capsule of superior tibiofibular joint': 'Capsule de l’articulation tibio-fibulaire proximale',
  'Anterior ligament of fibular head': 'Ligament antérieur de la tête fibulaire',
  'Posterior ligament of fibular head': 'Ligament postérieur de la tête fibulaire',
  'Interosseous membrane of leg': 'Membrane interosseuse de la jambe',
  'Anterior tibiofibular ligament': 'Ligament tibio-fibulaire antérieur',
  'Posterior tibiofibular ligament': 'Ligament tibio-fibulaire postérieur',
  'Transverse tibiofibular ligament': 'Ligament tibio-fibulaire transverse',
  'Posterior tibiotalar ligament': 'Ligament tibio-talaire postérieur',
  'Tibiocalcaneal ligament': 'Ligament tibio-calcanéen',
  'Tibionavicular ligament': 'Ligament tibio-naviculaire',
  'Anterior talofibular ligament': 'Ligament talo-fibulaire antérieur',
  'Posterior talofibular ligament': 'Ligament talo-fibulaire postérieur',
  'Calcaneofibular ligament': 'Ligament calcanéo-fibulaire',
  'Lateral talocalcaneal ligament': 'Ligament talo-calcanéen latéral',
  'Medial talocalcaneal ligament': 'Ligament talo-calcanéen médial',
  'Posterior talocalcaneal ligament': 'Ligament talo-calcanéen postérieur',
  'Anterior talocalcaneal ligament': 'Ligament talo-calcanéen antérieur',
  'Talocalcaneal interosseous ligament': 'Ligament talo-calcanéen interosseux',
  'Talonavicular ligament': 'Ligament talo-naviculaire',
  'Calcaneonavicular ligament': 'Ligament calcanéo-naviculaire',
  'Calcaneocuboid ligament': 'Ligament calcanéo-cuboïdien',
  'Plantar calcaneonavicular ligament': 'Ligament calcanéo-naviculaire plantaire',
  'Plantar calcaneocuboid ligament': 'Ligament calcanéo-cuboïdien plantaire',
  'Long plantar ligament': 'Ligament plantaire long',
  'Dorsal cuneonavicular ligaments': 'Ligaments cunéo-naviculaires dorsaux',
  'Plantar cuneonavicular ligaments': 'Ligaments cunéo-naviculaires plantaires',
  'Cuneocuboid interosseous ligament': 'Ligament cunéo-cuboïdien interosseux',
  'Plantar cuneocuboid ligament': 'Ligament cunéo-cuboïdien plantaire',
  'Intercuneiform interosseous ligaments': 'Ligaments intercunéiformes interosseux',
  'Dorsal intercuneiform ligaments': 'Ligaments intercunéiformes dorsaux',
  'Plantar intercuneiform ligaments': 'Ligaments intercunéiformes plantaires',
  'Dorsal tarsometatarsal ligaments': 'Ligaments tarso-métatarsiens dorsaux',
  'Plantar tarsometatarsal ligaments': 'Ligaments tarso-métatarsiens plantaires',
  'Cuneometatarsal interosseous ligaments': 'Ligaments cunéo-métatarsiens interosseux',
  'Dorsal metatarsal ligaments': 'Ligaments métatarsiens dorsaux',
  'Plantar metatarsal ligaments': 'Ligaments métatarsiens plantaires',
  'Metatarsal interosseous ligaments': 'Ligaments métatarsiens interosseux',
  'Deep transverse metatarsal ligament': 'Ligament métatarsien transverse profond',
  'Intersesamoid ligament': 'Ligament intersésamoïdien',
  'Articular capsules of metatarsophalangeal joints': 'Capsules des articulations métatarso-phalangiennes',
  'Collateral metatarsophalangeal ligaments': 'Ligaments collatéraux métatarso-phalangiens',
  'Plantar metatarsophalangeal ligaments': 'Ligaments plantaires métatarso-phalangiens',
  'Articular capsules of proximal interphalangeal joints of foot': 'Capsules des articulations interphalangiennes proximales du pied',
  'Articular capsules of distal interphalangeal joints of foot': 'Capsules des articulations interphalangiennes distales du pied',
  'Articular capsule of interphalangeal joint of great toe': 'Capsule de l’articulation interphalangienne de l’hallux',
  'Collateral interphalangeal ligaments of foot': 'Ligaments collatéraux interphalangiens du pied',
  'Plantar interphalangeal ligaments': 'Ligaments plantaires interphalangiens',

  // --------------------------------------------------------- régions, peau
  'Frontal region': 'Région frontale',
  'Parietal region': 'Région pariétale',
  'Temporal region': 'Région temporale',
  'Occipital region': 'Région occipitale',
  'Mastoid region': 'Région mastoïdienne',
  'Auricular region': 'Région auriculaire',
  'Helix': 'Hélix',
  'Antihelix': 'Anthélix',
  'Crura of antihelix': 'Branches de l’anthélix',
  'Tragus': 'Tragus',
  'Antitragus': 'Antitragus',
  'Intertragic incisure': 'Incisure intertragique',
  'Scapha': 'Scapha',
  'Triangular fossa': 'Fosse triangulaire',
  'Concha of auricle': 'Conque de l’auricule',
  'Cavity of concha': 'Cavité de la conque',
  'Cymba conchae': 'Cymba de la conque',
  'Anterior notch of auricle': 'Incisure antérieure de l’auricule',
  'Apex of auricle': 'Apex de l’auricule',
  'Auricular tubercle': 'Tubercule auriculaire (de Darwin)',
  'Eminentia conchae': 'Éminence de la conque',
  'Eminentia fossae triangularis': 'Éminence de la fosse triangulaire',
  'Eminentia scaphae': 'Éminence de la scapha',
  'Fossa antihelica': 'Fosse anthélicienne',
  'Posterior auricular groove': 'Sillon auriculaire postérieur',
  'Orbital region': 'Région orbitaire',
  'Nasal region': 'Région nasale',
  'Oral region': 'Région orale',
  'Angle of mouth': 'Angle de la bouche',
  'Labial commissure': 'Commissure des lèvres',
  'Tubercle of upper lip': 'Tubercule de la lèvre supérieure',
  'Buccal region': 'Région buccale (jugale)',
  'Infra-orbital region': 'Région infra-orbitaire',
  'Mental region': 'Région mentonnière',
  'Mentolabial sulcus': 'Sillon mento-labial',
  'Nasolabial sulcus': 'Sillon naso-labial',
  'Parotideomasseteric region': 'Région parotido-massétérine',
  'Zygomatic region': 'Région zygomatique',
  'Submandibular triangle': 'Triangle submandibulaire',
  'Submental triangle': 'Triangle submental',
  'Carotid triangle': 'Triangle carotidien',
  'Muscular triangle': 'Triangle musculaire (omo-trachéal)',
  'Sternocleidomastoid region': 'Région sterno-cléido-mastoïdienne',
  'Lesser supraclavicular fossa': 'Petite fosse supraclaviculaire',
  'Greater supraclavicular fossa': 'Grande fosse supraclaviculaire',
  'Lateral region of neck': 'Région latérale du cou',
  'Posterior region of neck': 'Région postérieure du cou (nuque)',
  'Pectoral region': 'Région pectorale',
  'Mammary region': 'Région mammaire',
  'Inframammary region': 'Région inframammaire',
  'Infraclavicular fossa': 'Fosse infraclaviculaire',
  'Presternal region': 'Région présternale',
  'Deltopectoral triangle': 'Trigone delto-pectoral',
  'Lateral region of thorax': 'Région latérale du thorax',
  'Epigastric region': 'Région épigastrique',
  'Umbilical region': 'Région ombilicale',
  'Hypochondriac region': 'Hypocondre',
  'Hypogastric region': 'Région hypogastrique (pubienne)',
  'Inguinal region': 'Région inguinale',
  'Lateral region of abdomen': 'Région latérale de l’abdomen (flanc)',
  'Lumbar region': 'Région lombale',
  'Sacral region': 'Région sacrale',
  'Vertebral region': 'Région vertébrale',
  'Scapular region': 'Région scapulaire',
  'Infrascapular region': 'Région infrascapulaire',
  'Interscapular region': 'Région interscapulaire',
  'Triangle of auscultation': 'Triangle d’auscultation',
  'Anal region': 'Région anale',
  'Urogenital region': 'Région uro-génitale',
  'Deltoid region': 'Région deltoïdienne',
  'Anterior region of arm': 'Région antérieure du bras',
  'Posterior region of arm': 'Région postérieure du bras',
  'Anterior region of elbow': 'Région antérieure du coude',
  'Posterior region of elbow': 'Région postérieure du coude',
  'Anterior region of forearm': 'Région antérieure de l’avant-bras',
  'Posterior region of forearm': 'Région postérieure de l’avant-bras',
  'Lateral border of forearm': 'Bord latéral de l’avant-bras',
  'Medial border of forearm': 'Bord médial de l’avant-bras',
  'Anterior region of wrist': 'Région antérieure du poignet',
  'Posterior region of wrist': 'Région postérieure du poignet',
  'Palm': 'Paume de la main',
  'Dorsum of hand': 'Dos de la main',
  'Palmar surfaces of digits of hand': 'Faces palmaires des doigts',
  'Dorsal surfaces of digits of hand': 'Faces dorsales des doigts',
  'Hip region': 'Région de la hanche',
  'Gluteal region': 'Région glutéale (fessière)',
  'Gluteal fold': 'Pli fessier',
  'Anterior region of thigh': 'Région antérieure de la cuisse',
  'Posterior region of thigh': 'Région postérieure de la cuisse',
  'Femoral triangle': 'Trigone fémoral (de Scarpa)',
  'Anterior region of knee': 'Région antérieure du genou',
  'Posterior region of knee': 'Région postérieure du genou (poplitée)',
  'Anterior region of leg': 'Région antérieure de la jambe',
  'Posterior region of leg': 'Région postérieure de la jambe',
  'Anterior region of ankle': 'Région antérieure de la cheville',
  'Lateral retromalleolar region': 'Région rétromalléolaire latérale',
  'Medial retromalleolar region': 'Région rétromalléolaire médiale',
  'Dorsum of foot': 'Dos du pied',
  'Sole': 'Plante du pied',
  'Heel region': 'Région calcanéenne (talon)',
  'Lateral border of foot': 'Bord latéral du pied',
  'Medial border of foot': 'Bord médial du pied',
  'Lateral part of longitudinal arch of foot': 'Partie latérale de l’arche longitudinale du pied',
  'Medial part of longitudinal arch of foot': 'Partie médiale de l’arche longitudinale du pied',
  'Proximal transverse arch of foot': 'Arche transversale proximale du pied',
  'Distal transverse arch of foot': 'Arche transversale distale du pied',
  'Hallucial eminence': 'Éminence de l’hallux',
  'Metatarsal region': 'Région métatarsienne',
  'Dorsal surfaces of digits of foot': 'Faces dorsales des orteils',
  'Plantar surfaces of digits of foot': 'Faces plantaires des orteils',
  'Hairs of head': 'Cheveux',
  'Hairs of eyebrow': 'Sourcils',
  'Eyelashes': 'Cils',
  'Pubic hairs': 'Poils pubiens',
  'Nail plate': 'Ongles de la main',
  'Nail plate (foot)': 'Ongles du pied',
  'Perionyx': 'Périonyx',
  'Perionyx (foot)': 'Périonyx (pied)',

  // ------------------------------------------- insertions (the bone's side)
  // Attachments named after something that is not a muscle mesh of its own.
  'Pronator teres': 'Muscle rond pronateur',
  'Common flexor tendon': 'Tendon commun des fléchisseurs',
  'Common extensor tendon': 'Tendon commun des extenseurs',
  'Trochanteric insertion': 'Muscles pelvi-trochantériens',
};

/** Names built by rule rather than listed: the forty-seven discs and nuclei. */
export const RULES = [
  [/^Intervertebral disc (\w+-\w+)$/, (m) => `Disque intervertébral ${m[1]}`],
  [/^Nucleus pulposus (\w+-\w+)$/, (m) => `Nucléus pulposus ${m[1]}`],
];

/**
 * What the full body leaves out, and why.
 *
 * Sulci drawn as surfaces inside the cortex, the long tracts inside the
 * spinal cord, a few meshes whose names the source file lost, and the
 * duplicate "M2" and "M3" segments. None of them is something a student
 * taps to learn; drawn, they are clutter on top of what is.
 */
export const LEAVE_OUT = [
  /sulcus|sulci|Lat_Fis|Temporal plane|White matter of telencephalon/i,
  /(spino|cortico|tecto|vestibulo|reticulo)\w* tract$|Posterolateral tract|fasciculus proprius/i,
  /Intermediomedial nucleus|^Nucleus proprius$|Intermediolateral nucleus|reticular process|intermediate substance/i,
  /^\?+|\?x|\(\/\/Posterior/,
  /Central canal'$/,
];
