// Planches d'anatomie: drawings from Servier Medical Art (CC BY 4.0), picked
// one by one for normal anatomy — no disease, no drug, no molecule — and each
// given a French title written here. Servier's own captions are French but a
// word or two (« Cerveau willis »); the titles say what is drawn.
//
// The drawings carry no labels. They are put beside the 3D models as the page
// of an atlas is put beside the specimen: the shape, the layers, the section.
//
// scripts/fetch-planches.mjs turns each file into public/planches/<id>.webp
// and a thumbnail; the credit is printed under every plate.

export const PLANCHES_CREDIT = 'Servier Medical Art (smart.servier.com), CC BY 4.0 — format et taille adaptés';

export const GROUPS = [
  { id: 'os', name: 'Ostéologie et arthrologie' },
  { id: 'muscles', name: 'Myologie' },
  { id: 'coeur', name: 'Cœur' },
  { id: 'vaisseaux', name: 'Vaisseaux' },
  { id: 'nerveux', name: 'Système nerveux' },
  { id: 'sens', name: 'Organes des sens' },
  { id: 'respiratoire', name: 'Appareil respiratoire' },
  { id: 'digestif', name: 'Appareil digestif et denture' },
  { id: 'glandes', name: 'Glandes' },
  { id: 'urinaire', name: 'Appareil urinaire' },
  { id: 'genital', name: 'Appareil génital et sein' },
  { id: 'lymphatique', name: 'Système lymphatique' },
];

/** Which plates go with a system of Le corps entier. */
export const GROUPS_OF_LAYER = {
  squelette: ['os'], articulations: ['os'], muscles: ['muscles'], fascias: ['muscles'],
  arteres: ['vaisseaux', 'coeur'], veines: ['vaisseaux'], nerfs: ['nerveux'], snc: ['nerveux'],
  lymphe: ['lymphatique'], organes: ['digestif', 'respiratoire', 'urinaire', 'genital', 'glandes', 'sens', 'coeur'],
  genital: ['genital'], vessie: ['urinaire'], sein: ['genital'], bassin: ['os'], placenta: ['vaisseaux'],
};

/** id: Servier's own name for the image; g: group; t: the French title; file: the original. */
export const PLANCHES = [
  { id: "ear", g: "sens", t: "L’oreille : externe, moyenne et interne (coupe frontale)", file: "https://smart.servier.com/wp-content/uploads/2016/10/Oreille.png" },
  { id: "inner-ear", g: "sens", t: "Oreille interne : labyrinthe et osselets", file: "https://smart.servier.com/wp-content/uploads/2016/10/Oreille_interne.png" },
  { id: "organ-of-corti", g: "sens", t: "Organe spiral (de Corti)", file: "https://smart.servier.com/wp-content/uploads/2016/10/Organe_Corti.png" },
  { id: "abdominal-aorta", g: "vaisseaux", t: "Aorte abdominale et ses branches", file: "https://smart.servier.com/wp-content/uploads/2016/10/aorte_abdo.png" },
  { id: "afferent-arteriole", g: "urinaire", t: "Artériole afférente et glomérule rénal", file: "https://smart.servier.com/wp-content/uploads/2016/10/Artere_glomerule.png" },
  { id: "aorta-anatomical-diagram", g: "vaisseaux", t: "Aorte, vue latérale", file: "https://smart.servier.com/wp-content/uploads/2016/10/aorte2.png" },
  { id: "aorta", g: "vaisseaux", t: "Aorte et ses branches principales", file: "https://smart.servier.com/wp-content/uploads/2016/10/aorte.png" },
  { id: "diastole", g: "coeur", t: "Diastole ventriculaire", file: "https://smart.servier.com/wp-content/uploads/2016/10/diastole.png" },
  { id: "systole", g: "coeur", t: "Systole ventriculaire", file: "https://smart.servier.com/wp-content/uploads/2016/10/systole.png" },
  { id: "arterial-circulation-overview", g: "vaisseaux", t: "Système artériel", file: "https://smart.servier.com/wp-content/uploads/2016/10/Systeme_arteriel.png" },
  { id: "layered-representation-arterial-tunics", g: "vaisseaux", t: "Paroi artérielle : les trois tuniques", file: "https://smart.servier.com/wp-content/uploads/2016/10/Arteres_couches.png" },
  { id: "artery-wall", g: "vaisseaux", t: "Paroi artérielle en coupe (histologie)", file: "https://smart.servier.com/wp-content/uploads/2016/10/Paroi_artere.png" },
  { id: "venous-circulation", g: "vaisseaux", t: "Retour veineux : pompe musculaire et valvules", file: "https://smart.servier.com/wp-content/uploads/2016/10/Circu_veineuse_1.png" },
  { id: "smart-blood-flow", g: "vaisseaux", t: "Valvule veineuse", file: "https://smart.servier.com/wp-content/uploads/2016/10/Flux_sang_veine.png" },
  { id: "circulation", g: "vaisseaux", t: "Circulations systémique et pulmonaire (schéma)", file: "https://smart.servier.com/wp-content/uploads/2016/10/circulation.png" },
  { id: "smart-brain-arteries", g: "vaisseaux", t: "Artères de la base de l’encéphale", file: "https://smart.servier.com/wp-content/uploads/2016/10/cerveau_willis.png" },
  { id: "brain-circulation", g: "vaisseaux", t: "Artères du cerveau, face latérale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Circu_cerebrale1.png" },
  { id: "brain-arteries", g: "vaisseaux", t: "Artères de la tête, du cou et du cerveau", file: "https://smart.servier.com/wp-content/uploads/2016/10/Arteres_cerveau.png" },
  { id: "smart-brain-circulation", g: "vaisseaux", t: "Artères du cerveau, face médiale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Circu_cerebrale2.png" },
  { id: "capillaries", g: "lymphatique", t: "Capillaire lymphatique", file: "https://smart.servier.com/wp-content/uploads/2016/10/Capillaire_lymphatique.png" },
  { id: "smart-capillaries", g: "vaisseaux", t: "Réseau capillaire", file: "https://smart.servier.com/wp-content/uploads/2016/10/capillaires.png" },
  { id: "capillaries-blood-vessel", g: "lymphatique", t: "Capillaires sanguins et lymphatiques", file: "https://smart.servier.com/wp-content/uploads/2016/10/reseau_capillaire.png" },
  { id: "circle-of-willis", g: "vaisseaux", t: "Cercle artériel du cerveau (de Willis)", file: "https://smart.servier.com/wp-content/uploads/2016/10/Cercle_willis.png" },
  { id: "heart-coronary-artery-bypass-grafting", g: "coeur", t: "Cœur et artères coronaires, vue antérieure", file: "https://smart.servier.com/wp-content/uploads/2016/10/coeur_09.png" },
  { id: "leg-venous-circulation", g: "vaisseaux", t: "Veines profondes du membre inférieur", file: "https://smart.servier.com/wp-content/uploads/2016/10/Circu_veineuse_profonde_face.png" },
  { id: "fetal-circulation", g: "vaisseaux", t: "Circulation fœtale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Circulation_foetale.png" },
  { id: "head-and-neck-arteries", g: "vaisseaux", t: "Artères carotides et vertébrales", file: "https://smart.servier.com/wp-content/uploads/2016/10/arteres_tete.png" },
  { id: "heart-sections", g: "coeur", t: "Ventricules, coupe transversale", file: "https://smart.servier.com/wp-content/uploads/2016/10/coupe_coeur1.png" },
  { id: "heart-vascularization", g: "coeur", t: "Vascularisation du cœur : artères et veines coronaires", file: "https://smart.servier.com/wp-content/uploads/2016/10/Coeur_vascularisation.png" },
  { id: "ventricle", g: "coeur", t: "Cœur gauche, coupe longitudinale : valve mitrale et cordages", file: "https://smart.servier.com/wp-content/uploads/2016/10/ventricule_01.png" },
  { id: "bone-osteon-overview", g: "os", t: "Os compact : ostéons et canaux centraux (de Havers)", file: "https://smart.servier.com/wp-content/uploads/2016/10/structure_osseuse_02.png" },
  { id: "pulmonary-circulation", g: "respiratoire", t: "Cœur et vaisseaux pulmonaires", file: "https://smart.servier.com/wp-content/uploads/2016/10/circu_pulmo.png" },
  { id: "vein-cross-sectional", g: "vaisseaux", t: "Veine et valvules, coupe", file: "https://smart.servier.com/wp-content/uploads/2016/10/Veine_coupe.png" },
  { id: "vein-diagram", g: "vaisseaux", t: "Veines de la tête et du cou", file: "https://smart.servier.com/wp-content/uploads/2016/10/veines_tete.png" },
  { id: "venous-circulation-leg-view", g: "vaisseaux", t: "Veines superficielles du membre inférieur", file: "https://smart.servier.com/wp-content/uploads/2016/10/Circu_veineuse_superficielle_dos3.png" },
  { id: "smart-venous-system", g: "vaisseaux", t: "Système veineux", file: "https://smart.servier.com/wp-content/uploads/2016/10/Systeme_veineux_3.png" },
  { id: "colon", g: "digestif", t: "Gros intestin (côlon)", file: "https://smart.servier.com/wp-content/uploads/2016/10/colon.png" },
  { id: "anatomical-diagram-complete-digestive-apparatus", g: "digestif", t: "Appareil digestif", file: "https://smart.servier.com/wp-content/uploads/2016/10/syst_dig_complet_coupe_detachable.png" },
  { id: "intestinal-villi", g: "digestif", t: "Villosité intestinale", file: "https://smart.servier.com/wp-content/uploads/2016/10/epi_jejunon_ileon.png" },
  { id: "intestine-overview", g: "digestif", t: "Intestin grêle", file: "https://smart.servier.com/wp-content/uploads/2016/10/intestin.png" },
  { id: "mid-intestine", g: "digestif", t: "Intestin grêle en coupe : plis circulaires", file: "https://smart.servier.com/wp-content/uploads/2016/10/coupe_intestin_02.png" },
  { id: "liver-and-gallbladder", g: "digestif", t: "Foie et voies biliaires extrahépatiques", file: "https://smart.servier.com/wp-content/uploads/2016/10/foie_vesicule.png" },
  { id: "liver-overview", g: "digestif", t: "Lobule hépatique", file: "https://smart.servier.com/wp-content/uploads/2016/10/foie_coupe.png" },
  { id: "mouth", g: "respiratoire", t: "Cavités nasale et buccale, coupe sagittale", file: "https://smart.servier.com/wp-content/uploads/2016/10/bouche.png" },
  { id: "lymphatic-system-stomach", g: "lymphatique", t: "Lymphatiques et nœuds lymphatiques de l’estomac", file: "https://smart.servier.com/wp-content/uploads/2016/10/Estomac_syst_lymphatique.png" },
  { id: "oral-cavity", g: "digestif", t: "Cavité buccale", file: "https://smart.servier.com/wp-content/uploads/2017/03/oral-cavity.png" },
  { id: "pancreas-coronal", g: "glandes", t: "Pancréas et conduit pancréatique", file: "https://smart.servier.com/wp-content/uploads/2016/10/pancreas_coupe.png" },
  { id: "papillae", g: "sens", t: "Papilles linguales", file: "https://smart.servier.com/wp-content/uploads/2016/10/Papilles_gustatives.png" },
  { id: "smart-stomach-ov", g: "digestif", t: "Estomac, coupe : tuniques et muqueuse", file: "https://smart.servier.com/wp-content/uploads/2016/10/estomac_coupe.png" },
  { id: "rectum", g: "digestif", t: "Rectum et canal anal, coupe frontale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Rectum.png" },
  { id: "salivary-glands", g: "glandes", t: "Glandes salivaires principales", file: "https://smart.servier.com/wp-content/uploads/2016/10/Glandes_salivaires.png" },
  { id: "fundus-membrane", g: "digestif", t: "Glande gastrique (muqueuse fundique)", file: "https://smart.servier.com/wp-content/uploads/2016/10/muqueuse_fundique.png" },
  { id: "taste", g: "sens", t: "Bourgeons du goût", file: "https://smart.servier.com/wp-content/uploads/2016/10/Bourgeons_gustatifs.png" },
  { id: "adrenal-gland-overview", g: "glandes", t: "Vascularisation de la glande surrénale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Adrenal-Gland-Vessels.png" },
  { id: "tongue", g: "digestif", t: "Langue, face dorsale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Langue.png" },
  { id: "tooth", g: "digestif", t: "Dent et parodonte, coupe", file: "https://smart.servier.com/wp-content/uploads/2016/10/dent.png" },
  { id: "breast-sagittal", g: "genital", t: "Sein, coupe sagittale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Sein_02.png" },
  { id: "adrenal", g: "glandes", t: "Rein et glande surrénale", file: "https://smart.servier.com/wp-content/uploads/2016/10/rein_surrenale.png" },
  { id: "normal-thyroid", g: "glandes", t: "Glande thyroïde", file: "https://smart.servier.com/wp-content/uploads/2016/10/Thyroide_normale.png" },
  { id: "islet-of-langerhans", g: "glandes", t: "Îlot pancréatique (de Langerhans)", file: "https://smart.servier.com/wp-content/uploads/2016/10/langerhans_01.png" },
  { id: "smart-pituitary-gland", g: "glandes", t: "Hypophyse et système porte hypophysaire", file: "https://smart.servier.com/wp-content/uploads/2016/10/AHH_02.png" },
  { id: "testicle-ov", g: "genital", t: "Testicule et épididyme, coupe", file: "https://smart.servier.com/wp-content/uploads/2016/10/testicle-2.png" },
  { id: "uterus", g: "genital", t: "Utérus et annexes, coupe frontale", file: "https://smart.servier.com/wp-content/uploads/2016/10/uterus_1.png" },
  { id: "uterus-lateral-view", g: "genital", t: "Ovaire et trompe utérine : ovulation et fécondation", file: "https://smart.servier.com/wp-content/uploads/2016/10/uterus_2.png" },
  { id: "arm-bones", g: "os", t: "Os de l’avant-bras et de la main", file: "https://smart.servier.com/wp-content/uploads/2016/10/bras_01.png" },
  { id: "smart-bone", g: "os", t: "Os long : structure (coupe)", file: "https://smart.servier.com/wp-content/uploads/2016/10/os_01.png" },
  { id: "joint-elbow", g: "os", t: "Articulation synoviale, coupe", file: "https://smart.servier.com/wp-content/uploads/2016/10/articulation_01.png" },
  { id: "pelvis", g: "os", t: "Bassin osseux, vue antérieure", file: "https://smart.servier.com/wp-content/uploads/2016/10/bassin_01.png" },
  { id: "femur", g: "os", t: "Fémur", file: "https://smart.servier.com/wp-content/uploads/2016/10/femur_01.png" },
  { id: "musculature-back", g: "muscles", t: "Muscles du dos", file: "https://smart.servier.com/wp-content/uploads/2016/10/Monsieur_muscles_dos.png" },
  { id: "myofibril", g: "muscles", t: "Muscle squelettique : faisceaux et fibres", file: "https://smart.servier.com/wp-content/uploads/2016/10/Muscleanat_3.png" },
  { id: "normal-joint", g: "os", t: "Articulation synoviale normale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Articulation_normale.png" },
  { id: "bone-microarchitecture", g: "os", t: "Os spongieux : trabécules", file: "https://smart.servier.com/wp-content/uploads/2016/10/Microarchitecture_os_protelos.png" },
  { id: "vertebral-column-side", g: "os", t: "Colonne vertébrale et ses courbures, profil", file: "https://smart.servier.com/wp-content/uploads/2016/10/Colonne_normale2.png" },
  { id: "osteon", g: "os", t: "Ostéons, coupe transversale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Osteons.png" },
  { id: "sarcomere-and-sarcoplasmic-reticulum", g: "muscles", t: "Fibre musculaire striée : myofibrilles", file: "https://smart.servier.com/wp-content/uploads/2016/10/myocyte_01.png" },
  { id: "skeleton-face", g: "os", t: "Squelette, vue antérieure", file: "https://smart.servier.com/wp-content/uploads/2016/10/squelette_03.png" },
  { id: "skull", g: "os", t: "Crâne, vue latérale", file: "https://smart.servier.com/wp-content/uploads/2016/10/crane_01.png" },
  { id: "head-skull", g: "os", t: "Crâne, vue antérieure", file: "https://smart.servier.com/wp-content/uploads/2016/10/crane_02.png" },
  { id: "smooth-muscle-view", g: "muscles", t: "Fibre musculaire lisse", file: "https://smart.servier.com/wp-content/uploads/2016/10/Musclelisse02.png" },
  { id: "tendon-anatomy", g: "muscles", t: "Structure du tendon", file: "https://smart.servier.com/wp-content/uploads/2016/10/Tendon_structure.png" },
  { id: "vertebral-column-overview", g: "os", t: "Colonne vertébrale, vue antérieure", file: "https://smart.servier.com/wp-content/uploads/2016/10/colonne_03.png" },
  { id: "overview-vertebral-column", g: "nerveux", t: "Canal vertébral lombal et espace épidural", file: "https://smart.servier.com/wp-content/uploads/2016/10/Espace_epidural.png" },
  { id: "lymphatic-circulation", g: "lymphatique", t: "Système lymphatique", file: "https://smart.servier.com/wp-content/uploads/2016/10/Systeme_lymphatique.png" },
  { id: "smart-lymph-node", g: "lymphatique", t: "Nœud lymphatique : structure", file: "https://smart.servier.com/wp-content/uploads/2016/10/Ganglion_lympha_2.png" },
  { id: "spleen-ov", g: "lymphatique", t: "Rate", file: "https://smart.servier.com/wp-content/uploads/2016/10/rate_01.png" },
  { id: "brain-overview-smart", g: "nerveux", t: "Cerveau, vue supérieure", file: "https://smart.servier.com/wp-content/uploads/2016/10/Cerveau_02.png" },
  { id: "smart-brain-overview", g: "nerveux", t: "Encéphale, vue latérale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Cerveau_beau.png" },
  { id: "whole-brain", g: "nerveux", t: "Encéphale, coupe sagittale médiane", file: "https://smart.servier.com/wp-content/uploads/2016/10/cerveau_zones.png" },
  { id: "brain-area", g: "nerveux", t: "Lobes du cerveau", file: "https://smart.servier.com/wp-content/uploads/2016/10/cerveau_zones2.png" },
  { id: "hippocampus", g: "nerveux", t: "Hippocampe et système limbique", file: "https://smart.servier.com/wp-content/uploads/2016/10/hypocampe.png" },
  { id: "smart-brain-sections", g: "nerveux", t: "Coupe frontale du cerveau", file: "https://smart.servier.com/wp-content/uploads/2016/10/Coupe_cerveau_01.png" },
  { id: "brain-17", g: "nerveux", t: "Cervelet", file: "https://smart.servier.com/wp-content/uploads/2016/10/Cervelet1.png" },
  { id: "cerebrospinal-fluid", g: "nerveux", t: "Circulation du liquide cérébrospinal", file: "https://smart.servier.com/wp-content/uploads/2016/10/Fluide_cerebrospinal.png" },
  { id: "smart-dermatomes", g: "nerveux", t: "Dermatomes, vue postérieure", file: "https://smart.servier.com/wp-content/uploads/2016/10/Dermatomes2.png" },
  { id: "dermatomes", g: "nerveux", t: "Dermatomes, vue antérieure", file: "https://smart.servier.com/wp-content/uploads/2016/10/Dermatomes1.png" },
  { id: "brain-section", g: "nerveux", t: "Aires fonctionnelles du cortex cérébral", file: "https://smart.servier.com/wp-content/uploads/2016/10/Cerveau_zones_fonctionnelles.png" },
  { id: "meninges", g: "nerveux", t: "Méninges", file: "https://smart.servier.com/wp-content/uploads/2016/10/Meninges.png" },
  { id: "nerve", g: "nerveux", t: "Nerf périphérique, coupe transversale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Nerf.png" },
  { id: "nervous-system", g: "nerveux", t: "Système nerveux central et périphérique", file: "https://smart.servier.com/wp-content/uploads/2016/10/Systeme_nerveux.png" },
  { id: "neuromuscular-synapse-sagittal", g: "nerveux", t: "Jonction neuromusculaire", file: "https://smart.servier.com/wp-content/uploads/2016/10/synapse_08.png" },
  { id: "neuron-ov", g: "nerveux", t: "Neurone", file: "https://smart.servier.com/wp-content/uploads/2016/10/Neurone012.png" },
  { id: "sciatic-nerve", g: "nerveux", t: "Nerf ischiatique et plexus sacral", file: "https://smart.servier.com/wp-content/uploads/2016/10/Sciatique.png" },
  { id: "spinal-cord-ov", g: "nerveux", t: "Moelle spinale, coupe transversale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Moelle_epiniere.png" },
  { id: "sympathetic-nervous-system", g: "nerveux", t: "Système nerveux sympathique", file: "https://smart.servier.com/wp-content/uploads/2016/10/SNS.png" },
  { id: "ovary", g: "genital", t: "Ovaire : évolution des follicules", file: "https://smart.servier.com/wp-content/uploads/2016/10/ovaire_1.png" },
  { id: "uterine-cycle", g: "genital", t: "Cycle de l’endomètre", file: "https://smart.servier.com/wp-content/uploads/2016/10/Cycle_uterin.png" },
  { id: "smart-pulmonary-circulation", g: "respiratoire", t: "Échanges gazeux alvéolaires", file: "https://smart.servier.com/wp-content/uploads/2016/10/echanges_systemic_circulation.png" },
  { id: "bronchi-section-ov", g: "respiratoire", t: "Bronche, coupe transversale", file: "https://smart.servier.com/wp-content/uploads/2016/10/bronche_saine.png" },
  { id: "intrapulmonary-airways-lungs", g: "respiratoire", t: "Bronchioles et alvéoles", file: "https://smart.servier.com/wp-content/uploads/2016/10/poumon_10.png" },
  { id: "larynx-front-view", g: "respiratoire", t: "Larynx, vue antérieure", file: "https://smart.servier.com/wp-content/uploads/2016/10/Larynx.png" },
  { id: "lungs-11", g: "respiratoire", t: "Poumons et arbre trachéo-bronchique", file: "https://smart.servier.com/wp-content/uploads/2016/10/poumons_01.png" },
  { id: "nasal-cavity", g: "respiratoire", t: "Cavité nasale, coupe sagittale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Cavite_nasale.png" },
  { id: "olfactory-bulb-ov", g: "sens", t: "Bulbe et épithélium olfactifs", file: "https://smart.servier.com/wp-content/uploads/2016/10/Bulbles_olfactifs.png" },
  { id: "paranasal-sinuses", g: "respiratoire", t: "Sinus paranasaux", file: "https://smart.servier.com/wp-content/uploads/2016/10/Sinus.png" },
  { id: "kidney", g: "urinaire", t: "Rein, coupe frontale", file: "https://smart.servier.com/wp-content/uploads/2016/10/rein_01.png" },
  { id: "bladder", g: "urinaire", t: "Vessie, coupe frontale", file: "https://smart.servier.com/wp-content/uploads/2016/10/vessie.png" },
  { id: "kidney-overview", g: "urinaire", t: "Reins et vascularisation rénale", file: "https://smart.servier.com/wp-content/uploads/2016/10/rein_03.png" },
  { id: "smart-nephron-ov", g: "urinaire", t: "Néphron", file: "https://smart.servier.com/wp-content/uploads/2016/10/nephron_03.png" },
  { id: "smart-nephron", g: "urinaire", t: "Néphron et sa vascularisation", file: "https://smart.servier.com/wp-content/uploads/2016/10/nephron_02.png" },
  { id: "urinary-tract-overview", g: "urinaire", t: "Appareil urinaire masculin", file: "https://smart.servier.com/wp-content/uploads/2016/10/App_urinaire_homme.png" },
  { id: "urinary-tract", g: "urinaire", t: "Appareil urinaire féminin", file: "https://smart.servier.com/wp-content/uploads/2016/10/App_urinaire_femme.png" },
  { id: "eye-vitreous-body-2", g: "sens", t: "Globe oculaire, coupe sagittale", file: "https://smart.servier.com/wp-content/uploads/2016/10/Oeil_globe.png" },
  { id: "optical-pathways", g: "sens", t: "Voies optiques", file: "https://smart.servier.com/wp-content/uploads/2016/10/Voies_optiques.png" },
  { id: "retina", g: "sens", t: "Fond d’œil normal", file: "https://smart.servier.com/wp-content/uploads/2016/10/fond_01.png" },
  { id: "smart-retina", g: "sens", t: "Rétine : couches cellulaires", file: "https://smart.servier.com/wp-content/uploads/2016/10/retine_20.png" },
  { id: "tear-duct", g: "sens", t: "Appareil lacrymal", file: "https://smart.servier.com/wp-content/uploads/2016/10/Canal_lacrimal.png" },
  { id: "heart-vector", g: "coeur", t: "Cœur, vue antérieure", file: "https://smart.servier.com/wp-content/uploads/2016/10/coeur_seul.png" },
  { id: "smart-heart-ov", g: "coeur", t: "Cœur, vue postérieure", file: "https://smart.servier.com/wp-content/uploads/2016/10/coeur2.png" },
  { id: "smart-heart-sagittal", g: "coeur", t: "Cœur, coupe frontale : les quatre cavités", file: "https://smart.servier.com/wp-content/uploads/2016/10/coeur_01.png" },
  { id: "heart-conduction", g: "coeur", t: "Système de conduction du cœur", file: "https://smart.servier.com/wp-content/uploads/2016/10/coeur_13.png" },
  { id: "the-cardiac-cycle", g: "coeur", t: "Cycle cardiaque", file: "https://smart.servier.com/wp-content/uploads/2016/10/coeur_02.png" },
  { id: "adult-teeth", g: "digestif", t: "Denture permanente", file: "https://smart.servier.com/wp-content/uploads/2016/10/Dents_adultes01.png" },
  { id: "child-teeth", g: "digestif", t: "Denture temporaire", file: "https://smart.servier.com/wp-content/uploads/2016/10/Dents_enfants01.png" },
  { id: "muscular-contraction", g: "muscles", t: "Sarcomère : glissement des myofilaments", file: "https://smart.servier.com/wp-content/uploads/2016/10/Muscle_contrac1.png" },
];
